/**
 * Kanonische Buchliste (66 Bücher) mit deutschen Namen, Abkürzungen und
 * Zuordnung zu den Kanon-Gruppen der App.
 *
 * `source` ist der Verzeichnisname im Rohdatenbestand (wldeh/bible-api,
 * de-luther1912). Dort existiert der Tippfehler "1.chonik" – deshalb wird
 * der Quellname getrennt vom Anzeigenamen geführt.
 */

export const GROUPS = [
  { id: 'tora', label: 'Tora', testament: 'AT' },
  { id: 'geschichte-at', label: 'Geschichtsbücher', testament: 'AT' },
  { id: 'poesie', label: 'Poesie & Weisheit', testament: 'AT' },
  { id: 'propheten-gross', label: 'Große Propheten', testament: 'AT' },
  { id: 'propheten-klein', label: 'Kleine Propheten', testament: 'AT' },
  { id: 'evangelien', label: 'Evangelien', testament: 'NT' },
  { id: 'geschichte-nt', label: 'Geschichte der Kirche', testament: 'NT' },
  { id: 'paulusbriefe', label: 'Paulusbriefe', testament: 'NT' },
  { id: 'briefe', label: 'Allgemeine Briefe', testament: 'NT' },
  { id: 'prophetie-nt', label: 'Prophetie', testament: 'NT' },
];

/** id | Anzeigename | Abkürzung | Gruppe | Quellverzeichnis */
export const BOOKS = [
  ['1mo', '1. Mose', '1Mo', 'tora', '1.mose'],
  ['2mo', '2. Mose', '2Mo', 'tora', '2.mose'],
  ['3mo', '3. Mose', '3Mo', 'tora', '3.mose'],
  ['4mo', '4. Mose', '4Mo', 'tora', '4.mose'],
  ['5mo', '5. Mose', '5Mo', 'tora', '5.mose'],
  ['jos', 'Josua', 'Jos', 'geschichte-at', 'josua'],
  ['ri', 'Richter', 'Ri', 'geschichte-at', 'richter'],
  ['rut', 'Rut', 'Rut', 'geschichte-at', 'ruth'],
  ['1sam', '1. Samuel', '1Sam', 'geschichte-at', '1.samuel'],
  ['2sam', '2. Samuel', '2Sam', 'geschichte-at', '2.samuel'],
  ['1koe', '1. Könige', '1Kön', 'geschichte-at', '1.könige'],
  ['2koe', '2. Könige', '2Kön', 'geschichte-at', '2.könige'],
  ['1chr', '1. Chronik', '1Chr', 'geschichte-at', '1.chonik'],
  ['2chr', '2. Chronik', '2Chr', 'geschichte-at', '2.chronik'],
  ['esr', 'Esra', 'Esr', 'geschichte-at', 'esra'],
  ['neh', 'Nehemia', 'Neh', 'geschichte-at', 'nehemia'],
  ['est', 'Ester', 'Est', 'geschichte-at', 'esther'],
  ['hi', 'Hiob', 'Hi', 'poesie', 'hiob'],
  ['ps', 'Psalmen', 'Ps', 'poesie', 'psalmen'],
  ['spr', 'Sprüche', 'Spr', 'poesie', 'sprüche'],
  ['pred', 'Prediger', 'Pred', 'poesie', 'prediger'],
  ['hld', 'Hoheslied', 'Hld', 'poesie', 'hohelied'],
  ['jes', 'Jesaja', 'Jes', 'propheten-gross', 'jesaja'],
  ['jer', 'Jeremia', 'Jer', 'propheten-gross', 'jeremia'],
  ['klgl', 'Klagelieder', 'Klgl', 'propheten-gross', 'klagelieder'],
  ['hes', 'Hesekiel', 'Hes', 'propheten-gross', 'hesekiel'],
  ['dan', 'Daniel', 'Dan', 'propheten-gross', 'daniel'],
  ['hos', 'Hosea', 'Hos', 'propheten-klein', 'hosea'],
  ['joel', 'Joel', 'Joel', 'propheten-klein', 'joel'],
  ['am', 'Amos', 'Am', 'propheten-klein', 'amos'],
  ['obd', 'Obadja', 'Obd', 'propheten-klein', 'obadja'],
  ['jona', 'Jona', 'Jona', 'propheten-klein', 'jona'],
  ['mi', 'Micha', 'Mi', 'propheten-klein', 'micha'],
  ['nah', 'Nahum', 'Nah', 'propheten-klein', 'nahum'],
  ['hab', 'Habakuk', 'Hab', 'propheten-klein', 'habakuk'],
  ['zef', 'Zefanja', 'Zef', 'propheten-klein', 'zephanja'],
  ['hag', 'Haggai', 'Hag', 'propheten-klein', 'haggai'],
  ['sach', 'Sacharja', 'Sach', 'propheten-klein', 'sacharja'],
  ['mal', 'Maleachi', 'Mal', 'propheten-klein', 'maleachi'],
  ['mt', 'Matthäus', 'Mt', 'evangelien', 'matthäus'],
  ['mk', 'Markus', 'Mk', 'evangelien', 'markus'],
  ['lk', 'Lukas', 'Lk', 'evangelien', 'lukas'],
  ['joh', 'Johannes', 'Joh', 'evangelien', 'johannes'],
  ['apg', 'Apostelgeschichte', 'Apg', 'geschichte-nt', 'apostelgeschichte'],
  ['roem', 'Römer', 'Röm', 'paulusbriefe', 'römer'],
  ['1kor', '1. Korinther', '1Kor', 'paulusbriefe', '1.korinther'],
  ['2kor', '2. Korinther', '2Kor', 'paulusbriefe', '2.korinther'],
  ['gal', 'Galater', 'Gal', 'paulusbriefe', 'galater'],
  ['eph', 'Epheser', 'Eph', 'paulusbriefe', 'epheser'],
  ['phil', 'Philipper', 'Phil', 'paulusbriefe', 'philipper'],
  ['kol', 'Kolosser', 'Kol', 'paulusbriefe', 'kolosser'],
  ['1thess', '1. Thessalonicher', '1Thess', 'paulusbriefe', '1.thessalonicher'],
  ['2thess', '2. Thessalonicher', '2Thess', 'paulusbriefe', '2.thessalonicher'],
  ['1tim', '1. Timotheus', '1Tim', 'paulusbriefe', '1.timotheus'],
  ['2tim', '2. Timotheus', '2Tim', 'paulusbriefe', '2.timotheus'],
  ['tit', 'Titus', 'Tit', 'paulusbriefe', 'titus'],
  ['phlm', 'Philemon', 'Phlm', 'paulusbriefe', 'philemon'],
  ['hebr', 'Hebräer', 'Hebr', 'briefe', 'hebräer'],
  ['jak', 'Jakobus', 'Jak', 'briefe', 'jakobus'],
  ['1petr', '1. Petrus', '1Petr', 'briefe', '1.petrus'],
  ['2petr', '2. Petrus', '2Petr', 'briefe', '2.petrus'],
  ['1joh', '1. Johannes', '1Joh', 'briefe', '1.johannes'],
  ['2joh', '2. Johannes', '2Joh', 'briefe', '2.johannes'],
  ['3joh', '3. Johannes', '3Joh', 'briefe', '3.johannes'],
  ['jud', 'Judas', 'Jud', 'briefe', 'judas'],
  ['offb', 'Offenbarung', 'Offb', 'prophetie-nt', 'offenbarung'],
];
