/**
 * Kanonische Buchliste (66 Bücher) mit deutschen Namen, Abkürzungen und
 * Zuordnung zu den Kanon-Gruppen der App.
 *
 * `source` ist der Verzeichnisname im Rohdatenbestand (wldeh/bible-api,
 * de-luther1912). Dort existiert der Tippfehler "1.chonik" – deshalb wird
 * der Quellname getrennt vom Anzeigenamen geführt.
 *
 * `sourceEn` ist der entsprechende Name im englischen Bestand (en-kjv), aus
 * dem `fetch-kjv.mjs` den Vergleichstext holt.
 */

export const GROUPS = [
  { id: 'tora', label: 'Tora', testament: 'AT' },
  { id: 'geschichte-at', label: 'Geschichtsbücher', testament: 'AT' },
  { id: 'poesie', label: 'Poesie & Weisheit', testament: 'AT' },
  { id: 'propheten-gross', label: 'Große Propheten', testament: 'AT' },
  { id: 'propheten-klein', label: 'Kleine Propheten', testament: 'AT' },
  { id: 'evangelien', label: 'Evangelien', testament: 'NT' },
  { id: 'geschichte-nt', label: 'Geschichte der Kirche', testament: 'NT' },
  { id: 'paulusbriefe', label: 'Paulusbriefe', testament: 'NT' },
  { id: 'briefe', label: 'Allgemeine Briefe', testament: 'NT' },
  { id: 'prophetie-nt', label: 'Prophetie', testament: 'NT' },
];

/** id | Anzeigename | Abkürzung | Gruppe | Quellverzeichnis | engl. Quellverzeichnis */
export const BOOKS = [
  ['1mo', '1. Mose', '1Mo', 'tora', '1.mose', 'genesis'],
  ['2mo', '2. Mose', '2Mo', 'tora', '2.mose', 'exodus'],
  ['3mo', '3. Mose', '3Mo', 'tora', '3.mose', 'leviticus'],
  ['4mo', '4. Mose', '4Mo', 'tora', '4.mose', 'numbers'],
  ['5mo', '5. Mose', '5Mo', 'tora', '5.mose', 'deuteronomy'],
  ['jos', 'Josua', 'Jos', 'geschichte-at', 'josua', 'joshua'],
  ['ri', 'Richter', 'Ri', 'geschichte-at', 'richter', 'judges'],
  ['rut', 'Rut', 'Rut', 'geschichte-at', 'ruth', 'ruth'],
  ['1sam', '1. Samuel', '1Sam', 'geschichte-at', '1.samuel', '1samuel'],
  ['2sam', '2. Samuel', '2Sam', 'geschichte-at', '2.samuel', '2samuel'],
  ['1koe', '1. Könige', '1Kön', 'geschichte-at', '1.könige', '1kings'],
  ['2koe', '2. Könige', '2Kön', 'geschichte-at', '2.könige', '2kings'],
  ['1chr', '1. Chronik', '1Chr', 'geschichte-at', '1.chonik', '1chronicles'],
  ['2chr', '2. Chronik', '2Chr', 'geschichte-at', '2.chronik', '2chronicles'],
  ['esr', 'Esra', 'Esr', 'geschichte-at', 'esra', 'ezra'],
  ['neh', 'Nehemia', 'Neh', 'geschichte-at', 'nehemia', 'nehemiah'],
  ['est', 'Ester', 'Est', 'geschichte-at', 'esther', 'esther'],
  ['hi', 'Hiob', 'Hi', 'poesie', 'hiob', 'job'],
  ['ps', 'Psalmen', 'Ps', 'poesie', 'psalmen', 'psalms'],
  ['spr', 'Sprüche', 'Spr', 'poesie', 'sprüche', 'proverbs'],
  ['pred', 'Prediger', 'Pred', 'poesie', 'prediger', 'ecclesiastes'],
  ['hld', 'Hoheslied', 'Hld', 'poesie', 'hohelied', 'songofsolomon'],
  ['jes', 'Jesaja', 'Jes', 'propheten-gross', 'jesaja', 'isaiah'],
  ['jer', 'Jeremia', 'Jer', 'propheten-gross', 'jeremia', 'jeremiah'],
  ['klgl', 'Klagelieder', 'Klgl', 'propheten-gross', 'klagelieder', 'lamentations'],
  ['hes', 'Hesekiel', 'Hes', 'propheten-gross', 'hesekiel', 'ezekiel'],
  ['dan', 'Daniel', 'Dan', 'propheten-gross', 'daniel', 'daniel'],
  ['hos', 'Hosea', 'Hos', 'propheten-klein', 'hosea', 'hosea'],
  ['joel', 'Joel', 'Joel', 'propheten-klein', 'joel', 'joel'],
  ['am', 'Amos', 'Am', 'propheten-klein', 'amos', 'amos'],
  ['obd', 'Obadja', 'Obd', 'propheten-klein', 'obadja', 'obadiah'],
  ['jona', 'Jona', 'Jona', 'propheten-klein', 'jona', 'jonah'],
  ['mi', 'Micha', 'Mi', 'propheten-klein', 'micha', 'micah'],
  ['nah', 'Nahum', 'Nah', 'propheten-klein', 'nahum', 'nahum'],
  ['hab', 'Habakuk', 'Hab', 'propheten-klein', 'habakuk', 'habakkuk'],
  ['zef', 'Zefanja', 'Zef', 'propheten-klein', 'zephanja', 'zephaniah'],
  ['hag', 'Haggai', 'Hag', 'propheten-klein', 'haggai', 'haggai'],
  ['sach', 'Sacharja', 'Sach', 'propheten-klein', 'sacharja', 'zechariah'],
  ['mal', 'Maleachi', 'Mal', 'propheten-klein', 'maleachi', 'malachi'],
  ['mt', 'Matthäus', 'Mt', 'evangelien', 'matthäus', 'matthew'],
  ['mk', 'Markus', 'Mk', 'evangelien', 'markus', 'mark'],
  ['lk', 'Lukas', 'Lk', 'evangelien', 'lukas', 'luke'],
  ['joh', 'Johannes', 'Joh', 'evangelien', 'johannes', 'john'],
  ['apg', 'Apostelgeschichte', 'Apg', 'geschichte-nt', 'apostelgeschichte', 'acts'],
  ['roem', 'Römer', 'Röm', 'paulusbriefe', 'römer', 'romans'],
  ['1kor', '1. Korinther', '1Kor', 'paulusbriefe', '1.korinther', '1corinthians'],
  ['2kor', '2. Korinther', '2Kor', 'paulusbriefe', '2.korinther', '2corinthians'],
  ['gal', 'Galater', 'Gal', 'paulusbriefe', 'galater', 'galatians'],
  ['eph', 'Epheser', 'Eph', 'paulusbriefe', 'epheser', 'ephesians'],
  ['phil', 'Philipper', 'Phil', 'paulusbriefe', 'philipper', 'philippians'],
  ['kol', 'Kolosser', 'Kol', 'paulusbriefe', 'kolosser', 'colossians'],
  ['1thess', '1. Thessalonicher', '1Thess', 'paulusbriefe', '1.thessalonicher', '1thessalonians'],
  ['2thess', '2. Thessalonicher', '2Thess', 'paulusbriefe', '2.thessalonicher', '2thessalonians'],
  ['1tim', '1. Timotheus', '1Tim', 'paulusbriefe', '1.timotheus', '1timothy'],
  ['2tim', '2. Timotheus', '2Tim', 'paulusbriefe', '2.timotheus', '2timothy'],
  ['tit', 'Titus', 'Tit', 'paulusbriefe', 'titus', 'titus'],
  ['phlm', 'Philemon', 'Phlm', 'paulusbriefe', 'philemon', 'philemon'],
  ['hebr', 'Hebräer', 'Hebr', 'briefe', 'hebräer', 'hebrews'],
  ['jak', 'Jakobus', 'Jak', 'briefe', 'jakobus', 'james'],
  ['1petr', '1. Petrus', '1Petr', 'briefe', '1.petrus', '1peter'],
  ['2petr', '2. Petrus', '2Petr', 'briefe', '2.petrus', '2peter'],
  ['1joh', '1. Johannes', '1Joh', 'briefe', '1.johannes', '1john'],
  ['2joh', '2. Johannes', '2Joh', 'briefe', '2.johannes', '2john'],
  ['3joh', '3. Johannes', '3Joh', 'briefe', '3.johannes', '3john'],
  ['jud', 'Judas', 'Jud', 'briefe', 'judas', 'jude'],
  ['offb', 'Offenbarung', 'Offb', 'prophetie-nt', 'offenbarung', 'revelation'],
];
