/* Vertiefung: Johannes und Apostelgeschichte */

export const PATCHES = {
  'joh 10,10': {
    longAdd:
      'Die Hirtenrede setzt einen Streit fort. Unmittelbar davor steht die Heilung eines Blindgeborenen und dessen Ausschluss aus der Synagoge; die Rede vom Dieb und vom Hirten richtet sich an die, die diesen Ausschluss betrieben haben. Damit hat das Bild eine Schärfe, die beim Zitieren regelmäßig verlorengeht: Es unterscheidet nicht zwischen Glaube und Unglaube, sondern zwischen Verantwortlichen, die ihre Aufgabe erfüllen, und solchen, die sie zum eigenen Vorteil gebrauchen.\n\nDie Vorlage steht bei Hesekiel. Dort spricht der Prophet im babylonischen Exil und wirft den Hirten Israels vor, die Herde geschoren, aber nicht geweidet zu haben; gemeint sind Könige, Beamte und Priester. Als Antwort kündigt Gott an, selbst Hirte zu sein und einen einzigen Hirten einzusetzen. Wer in einer Auseinandersetzung mit der Tempelführung dieses Kapitel aufruft, zitiert nicht ein frommes Bild, sondern eine Anklage gegen die politische Führung.\n\nDer Hirte war zugleich ein Herrschertitel im ganzen Alten Orient. Hammurapi nennt sich im Vorwort seines Gesetzbuches Hirte seines Volkes, ägyptische Pharaonen führen den Krummstab, und homerische Könige heißen Hirten der Völker. Das Bild klingt heute idyllisch; damals bezeichnete es Amtsgewalt und die Pflicht zum Schutz. Die reale Arbeit war entsprechend hart: Hirten galten sozial als wenig angesehen, standen unter dem Verdacht, fremdes Land zu nutzen, und waren nach rabbinischen Texten als Zeugen umstritten.\n\nDas Wort, das Luther mit volle Genüge übersetzt, gehört in die Kaufmannssprache und meint das, was über das Maß hinausgeht – den Rest, der übrigbleibt, wenn genug da ist. Dasselbe Wort steht bei der Speisung der Fünftausend für die zwölf Körbe voll Brocken. Damit ist ein Maß gemeint, das sich zählen lässt, nicht eine innere Größe. Ob daraus Zusagen über materiellen Wohlstand abzuleiten sind, ist eine andere Frage, und der Zusammenhang – ein Hirte, der sein Leben lässt – legt keine nahe.',
  },
  'joh 11,25': {
    longAdd:
      'Die Vorstellungen von der Auferstehung waren in der Zeit umstritten. Die Sadduzäer, die den Tempel führten, lehnten sie ab, weil sie in den fünf Büchern Mose nicht ausgesprochen wird; die Pharisäer vertraten sie und beriefen sich auf Daniel und die Propheten. Josephus beschreibt den Streit als eine der Hauptunterscheidungen der Parteien, und die Apostelgeschichte erzählt, wie Paulus ihn vor dem Hohen Rat ausnutzt. Martha bekennt in ihrer Antwort die pharisäische Position – der Text lässt sie also nicht Unglauben, sondern eine damals verbreitete Lehre vertreten.\n\nDie Verschiebung liegt im Zeitwort. Auf die Erwartung eines Ereignisses am Jüngsten Tag antwortet ein Satz in der Gegenwart, und die beiden folgenden Sätze sind so gebaut, dass sie sich gegenseitig auslegen: Wer glaubt, wird leben, auch wenn er stirbt; wer lebt und glaubt, wird nicht sterben. Beide Sätze zusammen ergeben keine Aussage über die Lebensdauer, sondern verschieben, was Sterben bedeutet. Die johanneische Theologie nennt das die Gegenwart des Kommenden – ein Zug, der dieses Evangelium von den anderen unterscheidet.\n\nDie Erzählung selbst ist genau datiert und lokalisiert. Bethanien liegt etwa drei Kilometer von Jerusalem entfernt, am Osthang des Ölbergs; der Ort heißt heute el-Azarije, nach Lazarus. Die vier Tage, die der Text betont, haben einen Grund: Nach einer im Talmud überlieferten Vorstellung verweilte die Seele drei Tage beim Leib, danach war der Tod endgültig. Der vierte Tag schließt jede Möglichkeit einer Scheintod-Deutung aus – der Erzähler baut diesen Einwand aus.\n\nIn den anderen Evangelien fehlt die Geschichte vollständig, obwohl sie bei Johannes der unmittelbare Anlass für den Beschluss ist, Jesus zu töten. Diese Auffälligkeit ist eines der Standardprobleme der Evangelienforschung. Erklärungsversuche reichen von der Annahme, Markus habe die Erzählung nicht gekannt, über die Vermutung, sie habe zum Schutz der Beteiligten zurückgehalten werden müssen, bis zu der Auffassung, Johannes gestalte hier eine theologische Szene aus vorhandenen Motiven. Eine Entscheidung ist nicht in Sicht.',
  },
  'joh 13,34': {
    longAdd:
      'Warum das Gebot neu heißt, wo es alt ist, hat die Ausleger seit der Antike beschäftigt. Augustinus antwortete, neu sei nicht der Inhalt, sondern der Mensch, den es neu macht. Andere verweisen auf den Maßstab: Der alte Vergleichspunkt ist die Selbstliebe, der neue ist eine Handlung, die eben geschehen ist – die Fußwaschung – und eine, die bevorsteht. Eine dritte Erklärung stellt auf den Zeitpunkt ab: Neu heißt in der prophetischen Sprache, was zur kommenden Zeit gehört, wie der neue Bund bei Jeremia oder das neue Herz bei Hesekiel.\n\nDie Fußwaschung davor gibt dem Gebot seine Anschauung. Füße zu waschen war die Aufgabe des niedrigsten Sklaven im Haus; nach rabbinischen Texten konnte ein jüdischer Sklave sie verweigern. Wer sie freiwillig übernahm, gab damit den eigenen Rang preis. Petrus wehrt sich in der Erzählung genau deshalb. Dass der Auftrag anschließend mit einem Gebot verbunden wird, macht aus der Szene keine Zeremonie, sondern einen Maßstab.\n\nDer eingegrenzte Kreis – einander, nicht alle – ist der schwierigste Punkt. Er entspricht der Lage der johanneischen Gemeinden, die sich nach dem Bruch mit der Synagoge als bedrängte Minderheit verstanden; solche Gruppen richten ihre Ethik nach innen. Die Briefe desselben Kreises verschärfen das noch. Ausleger halten dagegen, dass die Fußwaschung Judas einschließt, der im selben Kapitel als Verräter benannt wird, und dass damit ein Zeichen gesetzt ist, das über den Kreis der Getreuen hinausgeht.\n\nDie Wirkung nach außen ist im Text ausdrücklich mitgedacht: Daran werden alle erkennen. Das setzt Beobachtung voraus. Antike Vereine hatten Satzungen über gegenseitige Hilfe, Begräbniskassen und gemeinsame Mahlzeiten; wer eine solche Gruppe von außen sah, verglich sie mit anderen. Kaiser Julian beklagte im vierten Jahrhundert, die Christen versorgten nicht nur ihre eigenen Armen, sondern auch die fremden, und forderte die heidnischen Priesterschaften auf, es ihnen gleichzutun – ein Zeugnis für die Wirkung von außen und zugleich dafür, dass das „einander“ in der Praxis überschritten wurde.',
  },
  'joh 14,27': {
    longAdd:
      'Der Ort des Satzes ist ein Abschied. Die Kapitel vierzehn bis siebzehn geben Reden wieder, die in der Nacht vor der Verhaftung gehalten werden; die Gattung ist bekannt: Abschiedsreden großer Gestalten stehen im Alten Testament bei Jakob, Mose und Josua, in der jüdischen Literatur der Zeit im Testament der zwölf Patriarchen. Sie folgen einem Muster – Ankündigung des Todes, Trost, Weisung, Vermächtnis. Ein Vermächtnis ist auch hier gemeint: Der Frieden wird ausdrücklich hinterlassen, mit einem Wort aus der Sprache der Erbschaft.\n\nDas hebräische Wort, das hinter dem griechischen steht, meint mehr als das Ausbleiben von Streit. Schalom bezeichnet Unversehrtheit, Vollständigkeit, ein Verhältnis, in dem nichts fehlt; es kann für Gesundheit stehen, für gute Nachbarschaft und für den Abschluss eines Vertrages. Das Verb dahinter bedeutet vollständig machen und ist mit dem Wort für Bezahlung verwandt. Der Gruß, in dem es täglich gebraucht wurde, war deshalb nicht bloß Höflichkeit, sondern ein Wunsch mit Inhalt.\n\nDer Frieden, von dem sich der Satz absetzt, hatte einen Namen und ein Denkmal. Die Pax Romana war ein Herrschaftsprogramm: Augustus ließ 9 vor Christus in Rom den Friedensaltar weihen, dessen Reliefs die Familie des Kaisers und die Fruchtbarkeit des Landes zeigen. Ihre Grundlage war militärische Überlegenheit; ein britannischer Fürst sagt bei Tacitus, die Römer machten eine Wüste und nennten es Frieden. Der Satz vom Geben, das anders ist als das der Welt, spricht in diese Erfahrung hinein.\n\nDas Verb, mit dem der Vers schließt, gehört zur Sprache der Furcht vor konkreter Gewalt. Dasselbe Wort beschreibt an anderer Stelle das Aufwühlen des Wassers und die Erschütterung Jesu selbst am Grab des Lazarus. Der Text verbietet damit keine Gefühle; er stellt der Angst etwas gegenüber, ohne sie zu bestreiten. Die seelsorgliche Auslegung des zwanzigsten Jahrhunderts hat darauf besonderes Gewicht gelegt, weil der Vers oft gebraucht wurde, um Angst als Glaubensmangel abzutun.',
  },
  'joh 15,5': {
    longAdd:
      'Der Weinstock war ein politisches Zeichen. Über dem Eingang zum Tempelgebäude hing nach dem Bericht des Josephus eine goldene Weinranke mit Trauben von Manneshöhe, gestiftet von Wohlhabenden; sie galt als eines der kostbarsten Stücke des Heiligtums. Auf den Münzen des ersten jüdischen Aufstands und später der Bar-Kochba-Erhebung erscheinen Weinblätter und Trauben. Wer das Bild auf sich bezieht, greift damit in einen besetzten Symbolraum – und die Zuhörer wussten das.\n\nDie prophetischen Vorlagen sind fast durchweg Anklagen. Jesaja erzählt vom Weinberg, der trotz aller Arbeit schlechte Trauben bringt und deshalb preisgegeben wird; Jeremia spricht von einem edlen Weinstock, der zu einem wilden entartet ist; Hesekiel fragt, wozu das Holz des Weinstocks noch tauge, wenn es keine Frucht bringt – nämlich zu nichts als zum Verbrennen. Nur der achtzigste Psalm bittet um Wiederherstellung. Vor diesem Hintergrund ist die Rede vom wahren Weinstock eine Antwort auf eine Klage, nicht ein neues Bild.\n\nDie Arbeit im Weinberg gibt dem Abschnitt seine Genauigkeit. Reben werden im Winter zurückgeschnitten, oft radikal; ohne Schnitt wuchert das Holz und die Frucht bleibt aus. Im Frühjahr werden zusätzlich unfruchtbare Triebe entfernt, damit die Kraft in die Trauben geht. Das griechische Wort für reinigen im vorangehenden Vers ist mit dem für Schneiden lautlich verwandt – ein Wortspiel, das im Deutschen verlorengeht. Der Ertrag kam frühestens im vierten Jahr; die Tora verbot vorher die Nutzung. Weinbau war damit die geduldigste Form der Landwirtschaft.\n\nDas Wort bleiben, das den Abschnitt trägt, hat im Johannesevangelium einen festen Sinn: Es bezeichnet ein Verhältnis, das Bestand hat, nicht ein Gefühl. Dasselbe Verb steht für das Wohnen des Geistes, für das Bleiben des Wortes und für die Wohnungen im Haus des Vaters. Der Schlusssatz, ohne mich könnt ihr nichts tun, ist im Griechischen ohne Abschwächung formuliert – wörtlich: nichts. Die Ausleger sind sich uneins, ob damit die Unmöglichkeit jeder guten Handlung gemeint ist oder nur die des Fruchtbringens, von dem der Abschnitt handelt.',
  },
  'apg 1,8': {
    longAdd:
      'Die Frage der Jünger unmittelbar davor ist die politische Frage der Zeit. Die Wiederherstellung des Reiches für Israel meint das Ende der Fremdherrschaft und die Sammlung der zerstreuten Stämme; sie steht in den Gebeten der Synagoge und in den Erwartungen der Aufstandsbewegungen. Die Antwort weist die Frage nicht als falsch zurück, sondern die Berechnung des Zeitpunkts. An die Stelle des Wann tritt eine Aufgabe – ein Zug, der das ganze lukanische Doppelwerk kennzeichnet.\n\nDas Wort für Zeugen ist ein Rechtsbegriff. Ein Zeuge sagt aus, was er gesehen hat, und haftet für seine Aussage; das jüdische Recht verlangte zwei oder drei Zeugen für eine Verurteilung. Die Apostelgeschichte gebraucht das Wort durchgehend in diesem Sinn und bindet es an Augenzeugenschaft: Wer Judas ersetzen soll, muss die ganze Zeit dabei gewesen sein. Erst im zweiten Jahrhundert verschiebt sich die Bedeutung zum Märtyrer, weil das Zeugnis so oft mit dem Tod endete. Der deutsche Ausdruck Blutzeuge bewahrt beide Bedeutungen.\n\nWas mit dem Ende der Erde gemeint war, lässt sich eingrenzen. Die Wendung stammt aus Jesaja, wo sie den Auftrag an den Gottesknecht beschreibt. In der geographischen Literatur der Zeit galten je nach Standpunkt Spanien, Äthiopien oder Indien als Grenze der bewohnten Welt; Strabon beschreibt die Oikumene als Insel im Ozean. Lukas lässt seine Erzählung in Rom enden – nicht am Rand, sondern in der Mitte des Reiches. Ob er Rom als Erfüllung versteht oder als Sprungbrett, ist die Streitfrage der Auslegung; das Ende ohne Abschluss lässt beides zu.\n\nDie Reihenfolge der Stationen hat eine unbequeme Seite. Samarien war für die judäische Bevölkerung nicht ein weiteres Gebiet, sondern der Ort eines alten Bruchs: Die Samaritaner hatten einen eigenen Tempel auf dem Garizim, den ein hasmonäischer Herrscher im zweiten vorchristlichen Jahrhundert zerstören ließ, und galten als abtrünnig. Josephus berichtet von blutigen Zwischenfällen an den Wallfahrtsstraßen. Dass Samarien im Auftrag ausdrücklich genannt wird, bedeutet, dass der erste Schritt über die Grenze nicht zu Fremden führt, sondern zu Verfeindeten.',
  },
  'apg 4,12': {
    longAdd:
      'Die Szene ist ein Verfahren mit klaren Rollen. Petrus und Johannes sind über Nacht in Gewahrsam genommen worden, weil sie im Tempelbezirk gelehrt hatten; am Morgen tagt der Rat mit den Hohenpriestern. Die Anklage ist keine Lehrfrage, sondern eine Zuständigkeitsfrage: In wessen Vollmacht habt ihr das getan? Solche Verfahren sind aus der Zeit bekannt, und der Tempelbezirk unterstand einer eigenen Aufsicht mit Polizeigewalt. Die Antwort des Petrus ist deshalb eine Verteidigungsrede, kein Religionsvergleich.\n\nDas Wort, um das alles kreist, ist der Name. Im Semitischen steht der Name für die Person selbst und für ihre Vollmacht; Handlungen im Namen eines anderen waren rechtlich verbindlich. In der Heilungsgeschichte zwei Kapitel zuvor steht dieselbe Formel, und die Frage des Rates greift sie auf. Der Satz beansprucht also zunächst, dass die Heilung dieser Vollmacht zuzurechnen ist – und weitet das dann auf die Rettung überhaupt aus.\n\nDas griechische Verb, das Luther mit selig werden übersetzt, bedeutet zugleich heilen, bewahren und retten; dieselbe Wurzel steht im Namen Jesus, hebräisch Jeschua, „der Herr rettet“. Diese Verbindung ist im Griechischen hörbar und wird in der Rede vermutlich mitgemeint. Die deutsche Übersetzung mit selig werden verengt den Satz auf ein Jenseits, das im Zusammenhang einer Heilungsgeschichte gar nicht im Blick ist.\n\nÜber die Reichweite des Satzes wird seit dem 19. Jahrhundert gestritten. Die Frage, ob eine Aussage, die in einem innerjüdischen Verhör fällt, das Verhältnis zu Religionen beschreibt, die den Sprechenden unbekannt waren, ist eine Frage der Auslegungslehre, nicht des Wortlauts. Die kirchlichen Stellungnahmen des zwanzigsten Jahrhunderts gehen auseinander: Das Zweite Vatikanische Konzil hielt am einzigen Mittler fest und sprach zugleich von Wahrem und Heiligem in anderen Religionen; die Lausanner Verpflichtung von 1974 betont die Ausschließlichkeit; liberale und pluralistische Entwürfe deuten den Satz als Bekenntnissprache, die nicht über andere urteilt. Alle drei berufen sich auf denselben Vers.',
  },
  'apg 16,31': {
    longAdd:
      'Philippi war keine gewöhnliche Provinzstadt. Augustus hatte sie nach der Schlacht von 42 vor Christus zur römischen Kolonie gemacht und Veteranen dort angesiedelt; die Stadt besaß italisches Recht, ihre Beamten hießen wie in Rom, und Latein war Amtssprache. Die Erzählung nennt die Beamten mit dem korrekten Titel und lässt Paulus sich am Ende auf sein römisches Bürgerrecht berufen, dessen Missachtung ein ernstes Vergehen war. Der Kerkermeister war vermutlich selbst ein gedienter Soldat.\n\nSeine Reaktion ist rechtlich begründet. Wer Gefangene entkommen ließ, haftete mit dem eigenen Leben; das römische Recht kannte diese Regel, und die Erzählung von Petrus im Gefängnis setzt sie ebenfalls voraus. Der Griff zum Schwert ist deshalb kein Verzweiflungsakt, sondern die Vorwegnahme einer Hinrichtung – Selbsttötung galt in römischen Augen als ehrenhafterer Ausweg. Seine Frage nach der Rettung hat vor diesem Hintergrund zunächst einen handfesten Sinn, den der Text dann weiterführt.\n\nDas Haus, von dem die Antwort spricht, war eine Rechts- und Wirtschaftseinheit. Ihm gehörten Frau und Kinder an, dazu Sklaven, Freigelassene und mitunter Angestellte; über Kult und Bündnisse entschied der Hausvorstand für alle. Die Apostelgeschichte erzählt mehrere solcher Bekehrungen: Lydia und ihr Haus in derselben Stadt, Kornelius in Cäsarea, Krispus in Korinth. Was für heutige Leser wie eine Übergehung persönlicher Entscheidung aussieht, war die übliche Form, in der eine Gruppe ihre Zugehörigkeit änderte.\n\nGenau daran hängt die konfessionelle Streitfrage. Ob Kinder mitgemeint sind, lässt sich aus dem Wort Haus allein nicht entscheiden; der nächste Vers spricht davon, dass allen im Haus das Wort verkündigt wurde, was ein Verstehen voraussetzt. Die Kirchen, die Kinder taufen, verweisen auf die Einheit des Hauses und auf die Beschneidung als Vorbild; baptistische und täuferische Traditionen verweisen auf Verkündigung und Antwort. Die Auseinandersetzung ist seit dem 16. Jahrhundert im Gang und hat in der Forschung des 20. Jahrhunderts – im Streit zwischen Joachim Jeremias und Kurt Aland – eine eigene, ausführlich dokumentierte Runde erlebt.',
  },
};
