/* Vertiefung: neutestamentliche Artikel mit bisher nur einem Absatz */

export const PATCHES = {
  'mt 5,14': {
    longAdd:
      'Die Anrede ist im Griechischen betont. Das „Ihr“ steht als eigenes Wort da, obwohl die Verbform es schon enthält – eine Hervorhebung, die im Deutschen kaum wiederzugeben ist. Sie hat einen Gegenüber: In der jüdischen Überlieferung heißen die Tora, Israel, Jerusalem und der Tempel Licht der Welt, einzelne Rabbinen werden so genannt, und im Buch Jesaja soll der Gottesknecht ein Licht der Heiden sein. Der Satz greift eine geprägte Wendung auf und legt sie einer Gruppe von Fischern und Handwerkern bei.\n\nDie Stadt auf dem Berge lässt sich nicht sicher bestimmen. Wer an Jerusalem denkt, hat die Wallfahrtstexte im Ohr, in denen die Völker zum Zion strömen, weil dort das Licht aufgeht. Andere verweisen auf die galiläische Landschaft selbst: Städte lagen aus Verteidigungsgründen auf Kuppen, und von den Hügeln um den See waren mehrere zugleich zu sehen. Eine dritte Deutung denkt an eine im Bau befindliche Stadt – Sepphoris, wenige Kilometer von Nazareth, wurde in Jesu Jugend von Herodes Antipas neu errichtet. Alle drei Lesarten sind vertreten; der Text entscheidet nicht.\n\nDas Salzwort unmittelbar davor gehört mit dazu. Beide Bilder beschreiben Stoffe, die nicht für sich selbst da sind: Salz würzt anderes, Licht macht anderes sichtbar. Beide werden mit einer Warnung verbunden – Salz kann fade werden, Licht kann gelöscht werden. Die Zusage ist damit keine Standortbestimmung, die von selbst gilt, sondern eine, die verloren gehen kann.\n\nDer Gedanke der Sichtbarkeit hatte in der Umwelt einen scharfen Beiklang. Vereine und Kulte, die sich absonderten, standen unter Verdacht; zugleich war öffentliche Wohltätigkeit die anerkannte Weise, Ansehen zu erwerben, und wurde auf Inschriften festgehalten. Der Nachsatz in Vers 16 nimmt genau diesen Mechanismus auf und dreht ihn um: Die guten Werke sollen gesehen werden, aber der Ruhm soll nicht bei den Handelnden bleiben. In einer Ehrgesellschaft war das eine bemerkenswerte Zumutung.',
  },
  'mt 6,33': {
    longAdd:
      'Die Rede vom Sorgen setzt Lebensbedingungen voraus, die sich beziffern lassen. In Galiläa lebte die Mehrheit von Kleinlandwirtschaft auf Parzellen, die kaum über den Eigenbedarf hinaus trugen. Auf die Ernte lagen der Zehnte und weitere Tempelabgaben, dazu die Steuern des Herodes Antipas und der Pacht- oder Schuldendienst. Schätzungen der Forschung gehen davon aus, dass ein Drittel bis zur Hälfte des Ertrags abfloss. Eine schlechte Ernte bedeutete Verschuldung, zwei bedeuteten den Verlust des Landes und den Abstieg in die Tagelöhnerei.\n\nVor diesem Hintergrund ist die Erwähnung der Heiden im Vers zuvor keine Herabsetzung fremder Frömmigkeit, sondern eine Beobachtung: Wer keine Zusage hat, muss selbst vorsorgen. Die griechische Popularphilosophie der Zeit gab auf dieselbe Lage eine andere Antwort. Die Kyniker predigten Bedürfnislosigkeit, die Stoiker die Unabhängigkeit von äußeren Gütern durch innere Haltung. Beide Wege setzen beim Einzelnen an. Der Text hier setzt bei einer Zusage an, die von außen kommt – ein Unterschied, den die Auslegung oft übergeht.\n\nDer Wortlaut selbst schwankt in den Handschriften. Ein Teil der Überlieferung hat nur „sein Reich“, ein anderer die volle Form „das Reich Gottes und seine Gerechtigkeit“; die Reihenfolge der beiden Glieder wechselt ebenfalls. Für den Sinn ist das erheblich, denn Gerechtigkeit meint bei Matthäus nicht einen Rechtszustand, sondern das Tun dessen, was Gottes Willen entspricht. Das Reich wird also nicht erwartet, sondern gesucht – und das Suchen hat eine praktische Gestalt.\n\nDer Schlussvers begrenzt den Zeitraum, für den man verantwortlich ist, auf den heutigen Tag. Diese Begrenzung hat eine Entsprechung im Vaterunser, das um das Brot für den heutigen Tag bittet, und im Manna der Wüstenerzählung, das sich nicht auf Vorrat sammeln ließ. Alle drei Texte arbeiten mit derselben Vorstellung: Versorgung ist tageweise und lässt sich nicht ansparen. Das ist für Menschen mit Vorratshaltung eine schwierige Aussage – und war für Tagelöhner eine Beschreibung ihrer Lage.',
  },
  'mt 7,7': {
    longAdd:
      'Der Spruch hat Parallelen über den Kanon hinaus. Lukas bringt ihn fast wörtlich, schließt aber mit dem Heiligen Geist als Gabe statt mit „Gutem“ – eine Verschiebung, die für lukanische Theologie kennzeichnend ist. Das Thomasevangelium überliefert eine kürzere Fassung, und im zweiten Jahrhundert zitieren mehrere Väter den Satz in wieder anderer Form. Das spricht dafür, dass er früh und in verschiedenen Gemeinden umlief, bevor er schriftlich festgehalten wurde.\n\nGebet war in der Umwelt kein spontaner Vorgang, sondern eine Ordnung. Fromme Juden beteten dreimal täglich, morgens, nachmittags und abends; das Achtzehnbittengebet bestand aus festen Formeln, an die sich freie Bitten anschließen konnten. Die Aufforderung, anhaltend zu bitten, trifft also auf eine geübte Praxis und verstärkt sie. Die griechischen Befehlsformen der Dauer, die im Deutschen verschwinden, beschreiben nichts Außergewöhnliches, sondern eine Gewohnheit.\n\nDas Neue Testament selbst behandelt die Zusage nicht als Automatismus. Lukas stellt ihr zwei Gleichnisse zur Seite, in denen die Erhörung erst nach beharrlichem Drängen kommt: der Freund, der nachts nicht aufstehen will, und die Witwe, die den Richter zermürbt. Beide Erzählungen setzen voraus, dass Bitten auf Widerstand trifft. Paulus schreibt von einer dreifach vorgetragenen Bitte, die abgelehnt wird, und die Gethsemane-Szene erzählt dasselbe von Jesus. Der Kanon enthält damit seine eigene Gegenprobe.\n\nDaraus ist eine der ältesten Denkaufgaben der christlichen Theologie geworden. Augustinus schrieb an eine römische Witwe namens Proba einen langen Brief über die Frage und antwortete, Gott gebe entweder das Erbetene oder etwas Besseres; das Bitten sei nicht dazu da, Gott zu informieren, sondern den Bittenden zu formen. Thomas von Aquin band die Zusage an das, was zum Heil führt. Die Reformatoren betonten die Verheißung als Grund des Betens. Keine dieser Antworten hebt die Spannung auf, und die Auslegung des 20. Jahrhunderts hat es meist aufgegeben, das zu versuchen.',
  },
  'mt 7,12': {
    longAdd:
      'Die Belege für vergleichbare Sätze reichen weit zurück und über viele Kulturen. In den Gesprächen des Konfuzius, im fünften vorchristlichen Jahrhundert, antwortet der Meister auf die Frage nach einem Wort, das für das ganze Leben gilt: Was du selbst nicht wünschst, tue anderen nicht an. Isokrates rät in einer Rede an einen jungen Fürsten, sich gegen andere so zu verhalten, wie man es von ihnen erwartet. Das Buch Tobit und der Aristeasbrief bringen die verneinte Form. In Indien steht sie im Mahabharata, in der ägyptischen Weisheit gibt es Vorformen. Der Satz ist also kein Sondergut, sondern eine der wenigen Regeln, die sich unabhängig immer wieder eingestellt haben.\n\nOb die positive Fassung mehr fordert als die verneinte, ist eine alte Streitfrage. Die verbreitete Behauptung, das Christentum verlange Handeln und das Judentum nur Unterlassen, hält der Prüfung nicht stand: Die hebräische Bibel kennt zahlreiche positive Gebote zur Fürsorge, und das Gebot der Nächstenliebe im Heiligkeitsgesetz ist positiv formuliert. Jüdische wie christliche Ausleger haben wiederholt darauf hingewiesen, dass die Gegenüberstellung mehr über die Absicht der Vergleichenden aussagt als über die Texte.\n\nDer Ort in der Bergpredigt gibt dem Satz sein Gewicht. Die Wendung von Gesetz und Propheten steht am Anfang des Hauptteils in Kapitel fünf und hier an seinem Ende; beide Stellen bilden eine Klammer um alles, was dazwischenliegt. Was so gerahmt wird, ist nicht als Ersatz der Gebote gemeint, sondern als ihr Zusammenhang. Solche Zusammenfassungen waren eine geläufige Aufgabe der Schulen: Man suchte den Grundsatz, aus dem sich das Einzelne ergibt.\n\nDie moderne Kritik setzt an der Maßstabsfrage an. Wer seine eigenen Wünsche zum Maß für andere macht, kann übergriffig werden – der Kranke, der keine Behandlung will, der Fremde, dessen Vorstellungen von Hilfe andere sind. George Bernard Shaw formulierte den Einwand zugespitzt: Man solle anderen nicht antun, was man sich selbst wünsche, denn ihr Geschmack könne verschieden sein. Ausleger halten dagegen, dass die Regel in der Bergpredigt neben dem Feindesliebegebot steht und dass ihre Anwendung Kenntnis des anderen voraussetzt – ein Vorbehalt, den der Wortlaut allerdings nicht ausspricht.',
  },
  'mt 11,28': {
    longAdd:
      'Die Nähe zu Jesus Sirach lässt sich Zeile für Zeile verfolgen. Im einundfünfzigsten Kapitel jener Schrift ruft die Weisheit die Ungebildeten zu sich, fordert sie auf, ihren Hals unter das Joch zu beugen, und verspricht, dass sie Ruhe finden werden – dieselbe Abfolge von Einladung, Joch und Ruhe. Sirach entstand um 180 vor Christus in Jerusalem und wurde von seinem Enkel ins Griechische übersetzt; hebräische Handschriften des Buches sind erst 1896 in der Genisa einer Kairoer Synagoge und später in Masada gefunden worden. Der Text war also verbreitet und bekannt. Wer hier spricht, nimmt die Rolle ein, die dort die Weisheit hat.\n\nDas Joch ist im rabbinischen Sprachgebrauch ein festes Bild mit mehreren Gliedern. Man spricht vom Joch des Himmelreichs, das beim Sprechen des täglichen Bekenntnisses auf sich genommen wird, vom Joch der Gebote und – als Gegenbegriff – vom Joch der Fremdherrschaft. Wer eines auf sich nimmt, wird vom anderen frei; das ist ein geläufiger Gedanke. Die Einladung führt deshalb nicht aus jeder Bindung heraus, sondern in eine bestimmte hinein, und der Vergleich, der folgt, richtet sich gegen ein anderes Joch, nicht gegen das Joch überhaupt.\n\nDie Belastung, von der die Rede ist, hatte einen wirtschaftlichen Kern. Die Bevölkerung Galiläas trug zwei Lasten zugleich: die religiösen Abgaben an den Tempel und die Steuern des Herodes Antipas, der zur selben Zeit Sepphoris ausbaute und Tiberias neu gründete. Bauprojekte dieser Größe wurden aus dem Land finanziert. Die Wörter, die Luther mit mühselig und beladen wiedergibt, gehören in die Sprache der Lastenträger; das zweite ist ein Partizip, das ein Aufgeladenwerden von außen beschreibt.\n\nWas angeboten wird, ist im Griechischen genauer, als die Übersetzung erkennen lässt. Das Wort für erquicken meint eine Rast im Arbeitsablauf, und zwei Verse später steht ein anderes Wort, das Ruhe für die Seelen verspricht – ein wörtliches Zitat aus Jeremia, wo der Prophet die Umkehr zu den alten Wegen anmahnt und dieselbe Ruhe verheißt. Die Einladung ist damit in eine Debatte gestellt: Sie beansprucht, das einzulösen, was Jeremia dem Volk seiner Zeit vergeblich angeboten hatte.',
  },
  'mt 22,37': {
    longAdd:
      'Der Zusammenhang bei Matthäus ist ein Streitgespräch in der Karwoche. Nacheinander treten Pharisäer, Sadduzäer und ein Gesetzeskundiger auf; die Fragen nach der Steuer an den Kaiser, nach der Auferstehung und nach dem größten Gebot bilden eine Reihe. Markus erzählt dieselbe Szene freundlicher: Dort lobt der Fragende die Antwort und bekommt zu hören, er sei nicht fern vom Reich Gottes. Lukas verlegt das Gespräch an eine andere Stelle und lässt den Gesetzeskundigen die beiden Gebote selbst nennen, worauf das Gleichnis vom barmherzigen Samariter folgt. Drei Evangelien, drei Zuschnitte derselben Überlieferung.\n\nDie Verbindung der beiden Gebote war nicht neu. Das Testament der zwölf Patriarchen, eine jüdische Schrift aus derselben Zeit, stellt Gottes- und Nächstenliebe mehrfach nebeneinander, und Philon von Alexandria ordnet die Zehn Gebote zwei Bereichen zu: der Frömmigkeit gegen Gott und der Gerechtigkeit gegen Menschen. Was Matthäus überliefert, steht also in einer laufenden Diskussion. Die Zuspitzung liegt im Schlusssatz: An diesen beiden hängt das ganze Gesetz und die Propheten – ein Bild vom Türangel, an dem eine Tür hängt.\n\nDas erste Zitat weicht vom hebräischen Wortlaut ab. Dort stehen Herz, Seele und Kraft; hier steht statt Kraft das Gemüt, und die griechische Bibelübersetzung schwankt an dieser Stelle ebenfalls. Markus nennt sogar vier Glieder. Die Aufzählung will keine Seelenlehre bieten, sondern den ganzen Menschen bezeichnen; ihre Ungenauigkeit ist ein Hinweis darauf, dass sie als Gesamtausdruck verstanden wurde und nicht als Liste von Vermögen.\n\nDas zweite Zitat stammt aus einem Kapitel, das von Löhnen, Waagen, Ernterändern und dem Umgang mit Fremden handelt. Der Nächste ist dort zunächst der Volksgenosse, doch wenige Verse später wird derselbe Satz ausdrücklich auf den Fremdling ausgeweitet, der im Land wohnt. Wie weit der Kreis reicht, war eine offene Frage der Zeit; die Qumran-Gemeinde zog ihn eng und schloss die Söhne der Finsternis aus. Die Erzählung vom Samariter beantwortet sie, indem sie die Frage umdreht: Nicht wer mein Nächster ist, sondern wem ich zum Nächsten werde.',
  },
  'mk 10,45': {
    longAdd:
      'Die Szene davor ist im Markusevangelium sorgfältig gebaut. Dreimal kündigt Jesus sein Leiden an, dreimal folgt ein Missverständnis der Jünger, dreimal eine Belehrung über den Weg der Nachfolge. Der Vers steht am Ende des dritten Durchgangs und fasst zusammen, was der ganze Mittelteil des Evangeliums entfaltet. Matthäus übernimmt ihn fast unverändert; Lukas hat an derselben Stelle eine andere Fassung, in der Jesus sagt, er sei unter ihnen wie ein Dienender – ohne das Wort Lösegeld.\n\nDieses Wort ist der Streitpunkt. Es stammt aus der Rechtssprache und bezeichnet die Summe, mit der ein Kriegsgefangener oder ein Schuldsklave freigekauft wurde; in der griechischen Bibel steht es auch für das Auslösen des Erstgeborenen und für die Befreiung aus Ägypten. Wichtig ist, was es dort nicht bezeichnet: Der Empfänger der Zahlung wird in keinem dieser Zusammenhänge zum Gegenspieler Gottes. Die spätere Vorstellung, der Preis sei dem Teufel entrichtet worden, ergibt sich aus der Metapher, nicht aus dem Vers.\n\nDie Wendung „für viele“ hat eine eigene Geschichte. Im Hebräischen und Aramäischen hat das Wort für viele oft einschließenden Sinn: die Menge, alle. Der Gottesknecht bei Jesaja trägt die Sünde der Vielen, und der Abendmahlsbericht bei Markus gebraucht dieselbe Formel. In der lateinischen Messe wurde daraus „pro multis“, was eine Einschränkung nahelegte; die Übersetzungsdebatte darüber hat die katholische Kirche bis in die Gegenwart beschäftigt und 2006 zu einer römischen Weisung geführt, bei „für viele“ zu bleiben, während viele Landessprachen zuvor „für alle“ gesagt hatten.\n\nDer historische Zusammenhang der Szene ist der Aufstieg nach Jerusalem. Jakobus und Johannes bitten um die Plätze rechts und links – die Ehrenplätze eines Thronsaals. Dass Jesus stattdessen vom Dienen spricht, kehrt die Ordnung um, in der die Zuhörer lebten: Dienst war die Sache von Sklaven und Frauen, und ein Freier, der bei Tisch bediente, hätte sein Ansehen verloren. Die Umkehrung ist keine fromme Wendung, sondern ein Eingriff in die Rangordnung, an der alles hing.',
  },
  'mk 16,15': {
    longAdd:
      'Die handschriftliche Lage ist ungewöhnlich gut dokumentiert. Der Codex Sinaiticus und der Codex Vaticanus, beide aus dem vierten Jahrhundert, enden mit Vers acht; in mehreren armenischen und georgischen Handschriften fehlt der Abschnitt ebenfalls oder trägt eine Anmerkung. Eusebius und Hieronymus berichten, dass die meisten griechischen Handschriften ihrer Zeit den Schluss nicht enthielten. Daneben existiert eine zweite, kürzere Ergänzung von zwei Sätzen, und einige Handschriften bieten beide nacheinander – ein deutliches Zeichen dafür, dass Abschreiber ein als unfertig empfundenes Ende auf verschiedene Weise zu heilen versuchten.\n\nWarum das Evangelium mit der Furcht der Frauen abbricht, ist seit langem umstritten. Eine Erklärung nimmt an, der ursprüngliche Schluss sei verloren gegangen – Schriftrollen und frühe Kodizes waren am Ende besonders gefährdet. Eine andere hält den Abbruch für gewollt: Das Evangelium endet mit einem Auftrag, der nicht ausgeführt wird, und überlässt die Fortsetzung den Lesern. Für diese Deutung spricht, dass Markus mehrfach mit offenen Enden arbeitet; gegen sie, dass der griechische Satz mit einer Partikel schließt, mit der ein Buch kaum enden konnte.\n\nDie Verbindung von Glaube, Taufe und Rettung in Vers sechzehn ist der theologisch folgenreichste Teil der Ergänzung. Auffällig ist die Asymmetrie: Verdammt wird, wer nicht glaubt – von der Taufe ist in der zweiten Hälfte nicht mehr die Rede. Genau diese Ungleichheit haben Augustinus und später die Reformatoren herangezogen, um zu bestreiten, dass die Taufe als solche entscheidet. Das Konzil von Trient erklärte 1546 die lateinische Bibel in ihrer überlieferten Gestalt für maßgeblich und damit auch diesen Abschnitt.\n\nDie folgenden Verse über Schlangen und Gift haben eine unmittelbare Wirkung entfaltet. In einigen Gemeinden der Appalachen wird seit dem frühen 20. Jahrhundert mit Giftschlangen umgegangen; mehrere Todesfälle sind gerichtsbekannt, und einzelne Bundesstaaten der USA haben die Praxis verboten. Dass ein Text, dessen späte Herkunft in den Ausgaben vermerkt ist, eine solche Wirkung haben kann, gilt in der Auslegungslehre als Musterfall für die Frage, wie textkritisches Wissen die Praxis erreicht – oder eben nicht.',
  },
  'lk 1,37': {
    longAdd:
      'Der Wortlaut ist genauer, als die Übersetzung nahelegt. Im Griechischen steht kein Satz über Möglichkeiten überhaupt, sondern: Kein Wort wird bei Gott unmöglich sein. Das Wort rhema übersetzt das hebräische dabar, das zugleich Wort und Sache bedeutet; die griechische Fassung von 1. Mose gebraucht dieselbe Wendung, als der Gast bei Abraham fragt, ob dem Herrn etwas unmöglich sei. Lukas zitiert also nicht nur den Gedanken, sondern die Formulierung – für Leser der griechischen Bibel war der Bezug hörbar.\n\nDamit steht die Ankündigung in einer Reihe. Sara, Rebekka, Rahel, die Mutter Simsons und Hanna bekommen ein Kind, nachdem es nicht mehr zu erwarten war; die Erzählungen folgen einem festen Muster aus Not, Ankündigung, Einwand und Zeichen. Lukas erzählt die Ankündigung an Elisabeth genau nach diesem Muster und die an Maria mit einer entscheidenden Abweichung: Nicht Unfruchtbarkeit oder Alter stehen im Weg, sondern dass sie noch keinen Mann erkannt hat. Das Muster wird aufgenommen und überboten.\n\nDie Auslegung hat sich lange an der Frage abgearbeitet, ob der Satz eine allgemeine Aussage über Gottes Allmacht enthält. Der Zusammenhang legt eine engere Lesart nahe: Es geht um die Zusage, die eben gegeben wurde, und um deren Verwirklichung – der Engel verweist im selben Atemzug auf Elisabeth als Beleg. Die verbreitete Verwendung des Verses als allgemeine Ermutigung geht darüber hinaus. Sie ist nicht falsch, aber sie nimmt einem Satz seine Anbindung, die im Text ausdrücklich hergestellt wird.\n\nDie Antwort Marias im nächsten Vers ist in der Auslegungsgeschichte das eigentliche Gewicht. Sie bezeichnet sich mit einem Wort, das die Sklavin meint, und stimmt zu. Ob darin Gehorsam, Einwilligung oder eine eigene Entscheidung gesehen wird, hat die Deutungen geteilt: Die mittelalterliche Theologie sprach vom Jawort, ohne das die Menschwerdung nicht geschehen wäre; die Reformatoren betonten den Glauben, der dem Wort vertraut; die feministische Auslegung des 20. Jahrhunderts hat gefragt, wie frei eine Zustimmung ist, um die ein Bote Gottes bittet, und wie das Wort Sklavin dabei mitklingt.',
  },
  'lk 9,23': {
    longAdd:
      'Das Kreuz war zur Zeit der Erzählung keine Metapher. Rom setzte die Kreuzigung gegen Sklaven, Aufrührer und Provinzbewohner ohne Bürgerrecht ein; sie war öffentlich, langsam und darauf angelegt, abzuschrecken. Nach dem Tod Herodes des Großen ließ der Statthalter Varus im Zuge der Aufstandsbekämpfung nach dem Bericht des Josephus zweitausend Menschen bei Jerusalem kreuzigen. Wer in Galiläa aufwuchs, hatte Kreuze gesehen. Dass der Verurteilte den Querbalken selbst zum Richtplatz trug, ist mehrfach bezeugt und gehörte zur Demütigung.\n\nDer Zusatz „täglich“ steht nur bei Lukas und markiert einen Übergang. Markus schreibt für Leser, denen die Verfolgung unmittelbar bevorstehen kann; Lukas schreibt eine Generation später für Gemeinden, in denen die meisten eines natürlichen Todes sterben werden. Sein Zusatz überträgt das Bild vom einmaligen Todesweg auf eine wiederkehrende Übung, ohne die Härte zu tilgen. Dieselbe Bewegung lässt sich an anderen Stellen des Werkes beobachten: Lukas übersetzt die Erwartung des nahen Endes in eine Anleitung zum Weiterleben.\n\nDas Wort für Selbstverleugnung ist dasselbe, mit dem wenige Kapitel später die Verleugnung des Petrus beschrieben wird. Diese Verbindung ist kaum zufällig: Wer sich selbst verleugnet, sagt von sich, was Petrus im Hof des Hohenpriesters von Jesus sagt – ich kenne den nicht. In einer Gesellschaft, in der Ehre über Familie und Stand vergeben wurde, hieß das nicht Selbstverachtung, sondern den Verzicht auf den Anspruch, den man von Herkunft wegen hatte.\n\nDie Wirkungsgeschichte hat den Satz in zwei Richtungen gezogen. Die eine führt über das Mönchtum zur täglichen Übung; die andere hat ihn Menschen vorgehalten, die Gewalt erlitten, und ihr Erdulden als Nachfolge gedeutet. Die Seelsorge des zwanzigsten Jahrhunderts hat dieser zweiten Linie widersprochen: Das Kreuz, von dem der Text spricht, wird aufgenommen, nicht auferlegt, und ein Leiden, das ein anderer zufügt, ist damit nicht gemeint. Diese Unterscheidung ist in Handreichungen zum Umgang mit häuslicher Gewalt inzwischen fest verankert.',
  },
};
