/* Vertiefung: übrige Briefe */

export const PATCHES = {
  '2kor 4,16': {
    longAdd:
      'Der Brief ist unter allen Paulusbriefen der persönlichste und zugleich der am schwersten zu ordnende. Die Forschung rechnet überwiegend damit, dass mehrere Schreiben zu einem zusammengefügt wurden: Die Kapitel zehn bis dreizehn wechseln unvermittelt in scharfen Ton, und Kapitel acht und neun behandeln die Kollekte zweimal. Der Anlass war ein Zerwürfnis mit der Gemeinde in Korinth, in dem Gegner die Zuverlässigkeit des Absenders bestritten – unter anderem mit dem Hinweis auf sein Aussehen und seine Rede.\n\nDie Aufzählung dessen, was er erlitten habe, ist deshalb keine Klage, sondern ein Gegenargument. Sie folgt der Form eines Leistungsberichts, wie ihn Feldherren und Amtsträger auf Inschriften hinterließen – die Tatenberichte des Augustus sind das berühmteste Beispiel –, kehrt aber den Inhalt um: Statt Siegen und Ehrungen stehen dort Schläge, Gefangenschaften und Schiffbrüche. Die Forschung nennt das einen Peristasenkatalog; die Gattung war bekannt, die Umkehrung nicht.\n\nDie Strafen sind bezifferbar. Neununddreißig Schläge waren das jüdische Höchstmaß, um die vorgeschriebene Zahl von vierzig sicher nicht zu überschreiten; sie wurden mit einer dreisträngigen Riemenpeitsche verabreicht und konnten tödlich enden. Rutenstreiche waren eine römische Strafe, die einem Bürger eigentlich nicht zustand. Wer fünfmal das eine und dreimal das andere überstanden hat, trägt sichtbare Folgen – und der Text spricht anschließend davon, das Sterben Jesu am Leib zu tragen.\n\nDie Gegenüberstellung von Sichtbarem und Unsichtbarem klingt nach platonischer Zweiweltenlehre und ist es nicht. Bei Platon steht die Welt der Ideen der Welt der Erscheinungen gegenüber – zwei Bereiche zugleich. Hier stehen zwei Zeiten nebeneinander: das Gegenwärtige, das vergeht, und das Kommende, das noch nicht zu sehen ist. Die griechische Wendung, die Luther mit „was zeitlich ist“ wiedergibt, meint wörtlich das Vorläufige. Der Unterschied zwischen beiden Denkmustern ist einer der klassischen Streitpunkte der Paulusforschung.',
  },
  '2kor 5,7': {
    longAdd:
      'Der Abschnitt gehört zu den wenigen Stellen, an denen das Neue Testament die Frage nach dem Zustand zwischen Tod und Auferstehung berührt. Die Antworten gehen auseinander: Der erste Thessalonicherbrief spricht von Entschlafenen, die bei der Wiederkunft auferstehen; das Lukasevangelium lässt den Mitgekreuzigten noch am selben Tag ins Paradies kommen; hier ist vom Ausziehen und Überkleidetwerden die Rede, und die Bilder greifen ineinander, ohne ein System zu ergeben. Die spätere Lehre vom Zwischenzustand ist ein Versuch, diese Aussagen zu ordnen, den der Text nicht selbst unternimmt.\n\nDas Bild vom Zelt stammt aus dem eigenen Handwerk. Zelte wurden aus grobem Ziegenhaargewebe genäht, das Kilikien, die Herkunftslandschaft des Absenders, in großen Mengen lieferte; das Material hieß nach der Landschaft cilicium. Zeltmacher arbeiteten auch an Segeln, Planen und Lederwaren. Ein Zelt ist per Bauart vorläufig: Man schlägt es auf und ab. Die Stiftshütte der Wüstenzeit war ebenfalls ein Zelt – der Bezug lag für Kenner der griechischen Bibel nahe.\n\nDas Wort, das Luther mit Schauen wiedergibt, meint eigentlich die Gestalt, die man sieht, nicht den Vorgang des Sehens. Wörtlich steht dort: nicht durch Gestalt. Damit ist gesagt, dass die Grundlage des gegenwärtigen Lebens nicht die sichtbare Erscheinung ist. Dass daraus eine Absage an Erkenntnis und Nachdenken gemacht wurde, hat mit dem Vers wenig zu tun; derselbe Brief argumentiert über Kapitel hinweg mit Gründen und erwartet Zustimmung.\n\nDer Zusammenhang ist eine Auseinandersetzung über Beurteilungsmaßstäbe. Die Gegner in Korinth hielten dem Absender vor, seine Erscheinung sei schwach und seine Rede nichts wert – ein Argument, das in einer Kultur, die Redekunst und Auftreten hoch bewertete, wirksam war. Wenige Verse später steht der Satz, man kenne von nun an niemanden mehr nach dem Fleisch. Der Vers vom Wandeln im Glauben gehört in diese Debatte: Er bestreitet, dass der Augenschein das letzte Wort hat.',
  },
  '2kor 5,17': {
    longAdd:
      'Der Ausdruck „neue Kreatur“ hat eine Vorgeschichte. Die jüdische Literatur der Zeit spricht von der Erneuerung der Schöpfung am Ende der Tage, und rabbinische Texte nennen einen Menschen, der zum Judentum übertritt, ein neugeborenes Kind. Jesaja verheißt einen neuen Himmel und eine neue Erde. Der griechische Wortlaut lässt beides offen: Man kann übersetzen „er ist eine neue Schöpfung“ oder „dann ist neue Schöpfung“ – im zweiten Fall geht es nicht um die Erneuerung eines Einzelnen, sondern um den Anbruch einer neuen Welt. Die Ausgaben und Übersetzungen entscheiden sich verschieden, und daran hängt, ob der Satz individuell oder kosmisch gelesen wird.\n\nDas Wort für Versöhnung stammt aus dem Bereich der Politik und des Privatrechts. Es bezeichnet die Beilegung eines Streits zwischen Parteien, den Friedensschluss zwischen Städten, die Wiederannahme eines Verstoßenen in die Familie. Im Opferkult kommt es nicht vor. Die Wortwurzel bedeutet tauschen oder wechseln: Ein Verhältnis wird ausgetauscht. Josephus gebraucht dasselbe Wort, wenn er von der Aussöhnung zwischen Feldherren berichtet.\n\nDie Richtung ist die eigentliche Neuerung. In der antiken Religion versöhnte der Mensch die Gottheit – durch Opfer, Gelübde, Sühnegaben; die Formel „damit die Götter gnädig seien“ steht auf zahllosen Inschriften. Hier ist Gott der Handelnde und der Mensch der Empfänger, und die Aufforderung lautet, sich versöhnen zu lassen. Diese Umkehrung ist in der Auslegungsgeschichte immer wieder verwischt worden, sobald die Versöhnung als Vorgang beschrieben wurde, der Gott umstimmt.\n\nDer letzte Vers des Abschnitts ist einer der umstrittensten Sätze des Neuen Testaments. Dass der Sündlose zur Sünde gemacht worden sei, hat die Lehre vom Strafaustausch begründet, wie sie seit der Reformationszeit in vielen Bekenntnisschriften steht. Andere Auslegungen verweisen darauf, dass das griechische Wort für Sünde in der Bibelübersetzung auch das Sündopfer bezeichnet, und lesen den Satz kultisch. Wieder andere sehen darin eine Teilhabeaussage: Er tritt in die Lage der Sünder ein, ohne dass ein Strafmaß verrechnet würde. Kritiker der Strafaustauschlehre halten ihr entgegen, sie stelle Gott gegen Gott – ein Einwand, der seit dem 19. Jahrhundert regelmäßig erhoben wird.',
  },
  'gal 5,22': {
    longAdd:
      'Die neun Begriffe lassen sich nicht sauber gruppieren, obwohl es oft versucht wurde. Ein verbreiteter Vorschlag ordnet sie in drei Dreiergruppen – Verhältnis zu Gott, zum Nächsten, zu sich selbst –, doch die Wörter sperren sich: Geduld und Freundlichkeit betreffen beides, Treue meint zugleich Glaube. Die Reihe ist wohl nicht systematisch gemeint, sondern aufzählend. Ihre Länge steht in Spannung zur Liste davor, die deutlich mehr Glieder hat und mit einem „und dergleichen“ endet – ein Zeichen dafür, dass keine der beiden Aufzählungen vollständig sein will.\n\nTugendlisten waren eine bekannte Gattung. Die Stoiker führten Kataloge von Eigenschaften des Weisen, die Popularphilosophie verbreitete sie, und in Qumran steht ein Text über die beiden Geister, in dem Wege des Lichts und Wege der Finsternis mit ihren jeweiligen Eigenschaften einander gegenübergestellt sind – der Aufbau entspricht dem hier fast genau. Was den Abschnitt unterscheidet, ist das Bild: Nicht Werke des Geistes stehen dort, sondern Frucht.\n\nDieses Wort trägt die Argumentation. Frucht wird nicht hergestellt; sie wächst, wenn die Bedingungen stimmen, und sie braucht Zeit. Der Brief kämpft gegen die Forderung, Heidenchristen müssten sich beschneiden lassen und die Gebote halten, und die Wortwahl ist Teil des Arguments: Was er beschreibt, lässt sich nicht anordnen. Der Singular verstärkt das – es ist eine Frucht mit neun Seiten, keine Sammlung von Einzelleistungen.\n\nDie unterschiedliche Zählung der Konfessionen geht auf die Übersetzung zurück. Die lateinische Fassung hat drei Begriffe mehr – Langmut, Bescheidenheit und Keuschheit erscheinen dort zusätzlich –, sodass die katholische Tradition zwölf Früchte zählt; der Katechismus führt sie so auf. Die griechischen Handschriften bieten überwiegend neun. Der Unterschied ist ein Beispiel dafür, wie eine Übersetzungsvariante über Katechismen und Kirchenfenster jahrhundertelang weiterwirkt.\n\nDer selten zitierte Nachsatz ist vorsichtig formuliert: Wider solche ist das Gesetz nicht. Das ist keine Aufhebung des Gesetzes, sondern die Feststellung, dass es gegen diese Dinge nichts vorzubringen hat. In einem Brief, der um die Geltung des Gesetzes streitet, ist diese Zurückhaltung bemerkenswert – der Text erklärt das Gesetz nicht für erledigt, sondern für in dieser Hinsicht unbeteiligt.',
  },
  'phil 2,3': {
    longAdd:
      'Philippi war eine römische Kolonie mit ausgeprägtem Rangbewusstsein. Grabinschriften aus der Stadt nennen Ämter, Militärdienst und Stiftungen; wer etwas darstellte, ließ es in Stein schreiben. Die Gemeinde spiegelt diese Gesellschaft: Der Brief nennt zwei Frauen, Evodia und Syntyche, die miteinander im Streit liegen, und ruft die Gemeinde zur Einmütigkeit. Die Ermahnung zur Demut hat damit einen Anlass, der im Brief selbst benannt wird.\n\nDas Wort für Demut ist in der griechischen Literatur vor dem Neuen Testament fast durchweg abwertend. Es bezeichnet die Gesinnung des Niedrigen, des Sklaven, des Unterworfenen; Epiktet gebraucht es als Tadel. Wer frei war, sollte Großgesinntheit zeigen – Aristoteles behandelt sie als Tugend und beschreibt den Großgesinnten als jemanden, der sich großer Dinge für wert hält und es auch ist. Vor diesem Hintergrund ist die Aufwertung des Wortes eine Umbesetzung, die auffiel.\n\nIhre Grundlage ist der Hymnus, der unmittelbar folgt. Er beschreibt einen Weg nach unten – Verzicht auf Rang, Knechtsgestalt, Tod am Kreuz – und dann die Erhöhung. Die Forschung hält den Text überwiegend für ein älteres Lied, das der Brief zitiert; dafür sprechen Rhythmus, Wortschatz und der Aufbau in Strophen. Die Ermahnung davor ist damit nicht Einleitung zu einer Lehre, sondern die Anwendung eines Liedes, das die Gemeinde vermutlich kannte.\n\nDie Kehrseite dieser Tugend ist gut dokumentiert. Selbstzurücknahme wurde über Jahrhunderte denen gepredigt, die ohnehin wenig hatten – Untergebenen, Frauen, Kolonisierten –, während sie bei den Mächtigen selten eingefordert wurde. Die feministische Theologie hat seit den 1960er Jahren darauf hingewiesen, dass die klassische Sündenlehre den Hochmut ins Zentrum stellt und damit ein Problem beschreibt, das nicht alle haben; Valerie Saiving formulierte 1960 als erste, dass Selbstverlust für viele Frauen die näherliegende Gefahr sei. Ausleger halten dagegen, dass der Vers ausdrücklich nicht Selbstverachtung verlangt, sondern den Blick auf das, was dem anderen fehlt – Vers vier sagt „nicht nur“, nicht „nicht“.',
  },
  'kol 3,23': {
    longAdd:
      'Sklaverei war in der Antike keine Randerscheinung. Schätzungen gehen davon aus, dass in Italien ein erheblicher Teil der Bevölkerung unfrei war, in den Städten des Ostens etwas weniger. Sklaven waren rechtlich Sachen: Sie konnten verkauft, verpfändet und vererbt werden, ihre Ehen hatten keinen rechtlichen Bestand, und ihre Aussage vor Gericht war nur unter Folter gültig. Zugleich waren die Lebenslagen sehr verschieden – ein Bergwerkssklave und ein Verwalter eines Stadthaushalts hatten wenig gemeinsam.\n\nGenau diese Spannbreite macht die Haustafel schwer zu beurteilen. Die Anweisung, von Herzen zu arbeiten, richtet sich an Menschen, die nicht kündigen konnten. Dass ihnen dabei ein Erbe zugesprochen wird, ist rechtlich eine Ungeheuerlichkeit: Sklaven konnten nicht erben, weil sie selbst Vermögensgegenstand waren. Der Satz überträgt einen Rechtsbegriff auf Menschen, denen er verwehrt war – und der folgende Satz stellt den Herren einen Herrn im Himmel gegenüber, mit dem ausdrücklichen Zusatz, dass bei ihm kein Ansehen der Person gilt.\n\nDie Wirkung dieser Verse ist zwiespältig geblieben. Über Jahrhunderte wurden sie zur Rechtfertigung der Sklaverei angeführt: Wenn die Schrift Sklaven Anweisungen gibt, so das Argument, verurteilt sie die Einrichtung nicht. Sklavenhalter in den amerikanischen Südstaaten ließen eigene Bibelausgaben drucken, in denen der Auszug aus Ägypten fehlte, die Haustafeln aber standen. Auf der Gegenseite beriefen sich Abolitionisten auf den Philemonbrief und auf den Satz, dass in Christus nicht Sklave noch Freier sei.\n\nDie Umdeutung zur Berufsethik ist ein Vorgang der Neuzeit. Luther bezog die Weisungen auf die Stände und erklärte jede ehrliche Arbeit für gottgefällig – gegen die Vorstellung, das klösterliche Leben sei höher. Der Calvinismus verschärfte den Gedanken zur Berufspflicht. Max Weber machte diesen Zusammenhang 1905 zum Gegenstand seiner Untersuchung über die protestantische Ethik. Der Weg vom Sklaven, der nicht gehen kann, zum Angestellten mit Arbeitsvertrag ist dabei selten mitbedacht worden; er ändert die Aussage des Verses erheblich.',
  },
  'hebr 13,5': {
    longAdd:
      'Der Hebräerbrief ist kein Brief im gewöhnlichen Sinn. Ihm fehlt das Präskript mit Absender und Empfänger; er bezeichnet sich selbst als Wort der Ermahnung – dieselbe Wendung, die in der Apostelgeschichte für eine Synagogenpredigt steht. Erst am Schluss kommen briefliche Züge hinzu. Verfasser und Adressaten sind unbekannt. Die alte Zuschreibung an Paulus wurde schon in der Alten Kirche bezweifelt: Origenes schrieb, wer den Brief geschrieben habe, wisse Gott allein. Vorgeschlagen wurden Barnabas, Apollos, Priska und andere.\n\nDie Adressaten hatten offenbar Verluste hinter sich. Ein früheres Kapitel erinnert sie daran, dass sie öffentlich beschimpft wurden und die Beschlagnahme ihres Besitzes mit Freuden hinnahmen. Vermögenseinziehung war eine übliche Nebenstrafe; sie traf nicht nur den Betroffenen, sondern seine Familie und war oft das eigentliche Druckmittel. Vor diesem Hintergrund ist die Ermahnung zur Genügsamkeit keine allgemeine Mahnung gegen Habgier, sondern die Ansprache an Menschen, die tatsächlich wenig haben.\n\nDas Zitat ist im Griechischen ungewöhnlich nachdrücklich. Der Satz enthält eine doppelte Verneinung mit fünf Verneinungspartikeln – eine Häufung, die keine deutsche Übersetzung wiedergeben kann. Der Wortlaut entspricht weder genau der hebräischen Bibel noch genau der griechischen Fassung; der Verfasser zitiert offenbar aus dem Gedächtnis oder aus einer Sammlung. Gesprochen wurde die Zusage ursprünglich zu Josua vor dem Einzug in ein Land, das erst zu gewinnen war – ihre Übertragung auf Menschen, die ihren Besitz verloren haben, kehrt die Lage um.\n\nDas Wort für Genügsamkeit hat eine philosophische Vorgeschichte. Die Stoiker sprachen von Autarkie, der Unabhängigkeit von äußeren Umständen; das verwandte Wort steht im Philipperbrief, wo der Absender sagt, er habe gelernt, sich genügen zu lassen. Der Unterschied liegt in der Begründung: Die Stoa gründet die Genügsamkeit auf die Einsicht in die Natur der Dinge, der Hebräerbrief auf eine Zusage. Das eine ist eine Haltung, das andere ein Verhältnis.',
  },
  '1petr 5,7': {
    longAdd:
      'Der erste Petrusbrief redet seine Leser mit Wörtern an, die einen Rechtsstatus bezeichnen: Fremdlinge und Beisassen. Beisassen waren Menschen, die dauerhaft an einem Ort lebten, ohne Bürger zu sein – ohne Stimmrecht, ohne Anspruch auf Landbesitz, oft mit besonderen Abgaben. Ob der Brief das wörtlich meint oder als Bild für die Lage der Christen gebraucht, ist umstritten; wahrscheinlich beides. Die genannten Provinzen liegen im Norden und Inneren Kleinasiens, in Gegenden, die von der Missionsgeschichte der Apostelgeschichte nicht abgedeckt sind.\n\nDie Bedrängnis, die der Brief voraussetzt, ist keine staatliche Verfolgung. Beschrieben werden Verleumdung, Schmähung und die Verwunderung der Nachbarn darüber, dass die Angeredeten nicht mehr mitmachen. Der Briefwechsel zwischen Plinius und Trajan, wenige Jahrzehnte später und aus derselben Gegend, zeigt, wie aus solcher Stimmung ein Verfahren werden konnte: Angezeigt wurde auf Betreiben der Nachbarschaft, nicht auf Anordnung von oben.\n\nDas Verb im Vers ist konkret. Es beschreibt das Aufwerfen einer Last auf ein Tragtier; dasselbe Wort steht in der Erzählung vom Einzug in Jerusalem, wo Kleider auf das Tier geworfen werden. Grammatisch hängt es am vorigen Satz: Demütigt euch, indem ihr eure Sorge auf ihn werft. Demut und Loslassen sind damit nicht zwei Aufforderungen, sondern eine – wer die Sorge abgibt, gibt zugleich den Anspruch auf, allein zurechtzukommen.\n\nDie Fortsetzung ist bemerkenswert. Unmittelbar nach der Zusage folgt die Aufforderung, nüchtern und wachsam zu sein, weil der Widersacher umhergeht wie ein brüllender Löwe. Der Text verbindet also Loslassen und Aufmerksamkeit, statt sie gegeneinander zu stellen. Das Löwenbild stammt aus dem Psalter und war in Kleinasien nicht abstrakt: Verurteilte wurden in Arenen wilden Tieren vorgeworfen, und die Bilder solcher Hinrichtungen waren aus Mosaiken und Erzählungen bekannt.',
  },
  '2petr 1,16': {
    longAdd:
      'Der Abschnitt beruft sich auf ein bestimmtes Ereignis: die Stimme auf dem heiligen Berg. Gemeint ist die Verklärung, die alle drei ersten Evangelien erzählen. Der Wortlaut der Himmelsstimme weicht hier von allen drei Fassungen leicht ab – ein Hinweis darauf, dass der Verfasser aus dem Gedächtnis oder aus einer eigenen Überlieferung zitiert. Der Anspruch, Augenzeuge gewesen zu sein, ist damit an eine Szene gebunden, in der nach den Evangelien nur drei Jünger dabei waren.\n\nDer Vorwurf, gegen den er sich richtet, ist präzise. Das Wort für Fabeln bezeichnet erdachte Geschichten ohne Anspruch auf Tatsächlichkeit; genau das warfen gebildete Zeitgenossen den neuen Religionsanbietern vor. Lukian von Samosata beschreibt im zweiten Jahrhundert einen Betrüger, der ein Orakel erfindet und damit reich wird, und spart nicht mit Spott über die Leichtgläubigkeit seiner Anhänger. Wer sich gegen diesen Vorwurf verteidigte, musste auf Augenzeugen verweisen – dieselbe Strategie verfolgt das Lukasevangelium in seinem Vorwort.\n\nDer eigentliche Streitpunkt ist das Ausbleiben der Wiederkunft. Zwei Kapitel später wird der Einwand wörtlich zitiert: Wo ist die Verheißung seiner Zukunft? Seit die Väter entschlafen sind, bleibt alles, wie es war. Die Antwort arbeitet mit dem Psalmwort, dass tausend Jahre vor Gott wie ein Tag sind, und mit dem Gedanken, die Verzögerung sei Geduld. Das ist die erste ausdrückliche Behandlung eines Problems, das die frühe Kirche prägte: Wie geht eine Bewegung weiter, deren Naherwartung sich nicht erfüllt hat?\n\nDer Satz über die Auslegung hat eine eigene Geschichte. Er lässt sich zweifach verstehen: Keine Weissagung entstammt eigenmächtiger Deutung durch den Propheten – dann geht es um die Entstehung –, oder keine Weissagung darf eigenmächtig ausgelegt werden – dann geht es um die Leser. Die zweite Lesart wurde in der Auseinandersetzung des 16. Jahrhunderts zum Argument gegen die private Schriftauslegung; das Konzil von Trient führte den Vers in diesem Sinn an. Die Grammatik spricht eher für die erste, weil der folgende Satz von der Entstehung handelt.',
  },
  '1joh 1,5': {
    longAdd:
      'Der Brief beginnt ohne Absender und Empfänger und liest sich eher wie eine Ansprache. Sein Anlass steht in Kapitel zwei: Eine Gruppe hat die Gemeinde verlassen, und der Verfasser deutet den Auszug als Beweis, dass sie nicht dazugehörte. Solche Spaltungen sind aus der Zeit mehrfach belegt; die Briefe des Ignatius von Antiochien, wenige Jahre später und aus derselben Gegend, kämpfen gegen ähnliche Positionen.\n\nWas die Gegner lehrten, lässt sich nur aus den Sätzen erschließen, die der Brief zurückweist. Vier Formeln werden zitiert und jeweils bestritten: Wir haben Gemeinschaft mit ihm; wir haben keine Sünde; wir haben nicht gesündigt; wir kennen ihn. Dahinter steht offenbar eine Frömmigkeit, die Erkenntnis über Lebensführung stellte und Sünde für ein Problem der Unwissenden hielt. Die Forschung sieht darin eine Frühform dessen, was im zweiten Jahrhundert als gnostisch bezeichnet wurde, ohne dass sich die Verbindung sicher ziehen ließe.\n\nDie Gegenüberstellung von Licht und Finsternis war weit verbreitet. In den Schriften von Qumran steht ein Text über die Söhne des Lichts und die Söhne der Finsternis, der die Menschheit in zwei Lager teilt; persische Religion, hellenistische Mysterien und die philosophische Literatur arbeiten mit derselben Bildwelt. Der Brief übernimmt sie und verschiebt sie an einem Punkt: Die Trennlinie verläuft nicht zwischen Gruppen, sondern durch das Verhalten – wer in der Finsternis wandelt und Gemeinschaft behauptet, lügt.\n\nDie Antwort auf den Vollkommenheitsanspruch ist bemerkenswert unaufgeregt. Sie besteht nicht in einer Verschärfung, sondern im Angebot des Bekennens, und sie begründet es mit der Treue und Gerechtigkeit Gottes, nicht mit der Reue des Menschen. Das griechische Wort für bekennen heißt wörtlich dasselbe sagen: Man stimmt zu, was ohnehin gilt. Aus diesen beiden Versen sind die Beichtformulare der Kirchen gebaut; kaum eines kommt ohne sie aus, und ihre Zweiteilung – Feststellung, dann Zusage – ist die Grundform des liturgischen Sündenbekenntnisses geblieben.',
  },
  '2joh 1,4': {
    longAdd:
      'Die Anweisung, bestimmte Lehrer nicht ins Haus zu nehmen, ist nur vor dem Hintergrund der Wandermission verständlich. Es gab keine Kirchengebäude; Gemeinden versammelten sich in Privatwohnungen, und wer als Lehrer reiste, war auf Aufnahme angewiesen, weil Gasthäuser teuer waren und als anrüchig galten. Ein Haus zu öffnen hieß deshalb, jemandem eine Versammlung zur Verfügung zu stellen. Die Verweigerung war keine Unhöflichkeit, sondern der Entzug der Bühne.\n\nDie Didache, eine Gemeindeordnung aus derselben Zeit oder wenig später, regelt denselben Vorgang mit erstaunlicher Nüchternheit: Ein Wanderprophet dürfe zwei Tage bleiben, beim dritten sei er ein falscher Prophet; wer Geld verlange, ebenso. Die frühen Gemeinden hatten also ein praktisches Problem und behandelten es mit praktischen Regeln. Der Brief steht in dieser Reihe, verschärft die Frage aber vom Verhalten zur Lehre.\n\nDer Streitpunkt wird ausdrücklich benannt: ob Jesus Christus im Fleisch gekommen sei. Dahinter steht die Schwierigkeit, die eine an griechischer Bildung geschulte Umwelt mit einem leiblich leidenden Gott hatte. Materie galt als das Geringere; ein Gott, der isst, schwitzt und stirbt, war denkbar unpassend. Die Lösung, sein Leib sei nur scheinbar gewesen, wird in der Kirchengeschichte Doketismus genannt und im zweiten Jahrhundert von Ignatius mit denselben Argumenten bekämpft.\n\nDer Gruß, der verweigert werden soll, war kein Höflichkeitswort. Wen man auf der Straße grüßte, dem bescheinigte man Zugehörigkeit; die rabbinische Literatur behandelt die Frage, wen man grüßen darf, als ernste Angelegenheit. Die Anweisung steht damit in offener Spannung zu anderen Texten des Neuen Testaments, die den Gruß an Feinde ausdrücklich verlangen. Die Auslegungsgeschichte hat diese Spannung selten ausgehalten: Sie hat entweder den einen Satz gegen den anderen ausgespielt oder den härteren auf einen eng begrenzten Fall beschränkt.',
    crossRefsAdd: [
      { book: '1joh', chapter: 4, verse: 2, note: 'Im Fleisch gekommen – dasselbe Kriterium' },
      { book: 'mt', chapter: 5, verse: 47, note: 'Den Gruß nicht auf die Eigenen beschränken' },
      { book: '3joh', chapter: 1, verse: 8, note: 'Die Gegenprobe: solche aufnehmen' },
      { book: '2joh', chapter: 1, verse: 12, note: 'Der Schluss des Briefes' },
    ],
  },
  '2thess 2,1': {
    longAdd:
      'Die Vorstellung eines Herrschers, der sich göttliche Verehrung anmaßt, hatte konkrete Vorbilder. Antiochus IV. ließ 167 vor Christus im Jerusalemer Tempel einen fremden Altar errichten – das Danielbuch nennt es den Greuel der Verwüstung. Caligula befahl im Jahr 40 nach Christus, sein Standbild im Tempel aufzustellen; nur sein Tod verhinderte die Ausführung, und Josephus wie Philon berichten ausführlich über die Panik, die der Befehl auslöste. Wer eine Generation später von einem Menschen schrieb, der sich in den Tempel Gottes setzt, griff auf eine erinnerte Erfahrung zurück.\n\nDas Wort für den Abfall bezeichnete ursprünglich den politischen Aufstand; die griechische Bibel gebraucht es für die Empörung gegen einen König und für den Abfall vom Bund. Beide Bedeutungen schwingen mit. Ob ein Abfall innerhalb der Gemeinden gemeint ist oder eine allgemeine Auflehnung, sagt der Text nicht – wie er überhaupt an entscheidenden Stellen unbestimmt bleibt, weil er die Angeredeten an eine mündliche Belehrung erinnert, die wir nicht kennen.\n\nDas gilt vor allem für das Zurückhaltende. Der Text spricht einmal von einem Etwas und einmal von einem Jemand, ohne beides zu erklären, und setzt voraus, dass die Leser es wissen. Die Vorschläge der Auslegung sind zahlreich: das römische Reich mit seiner Rechtsordnung, der Kaiser, ein Engel, die Verkündigung, die noch geschehen muss, Gott selbst, der Heilige Geist, in neuerer Zeit auch die Deutung, es handle sich um eine widergöttliche Macht. Augustinus bekannte, er wisse nicht, was gemeint sei – ein Satz, den seither viele Ausleger wiederholt haben.\n\nDie Wirkung dieser Unbestimmtheit ist verheerend gewesen. Weil die Gestalt nicht festgelegt ist, ließ sie sich beliebig besetzen. Im Mittelalter wurde sie auf Kaiser und Gegenpäpste bezogen, im 16. Jahrhundert von Luther auf das Papsttum und von katholischer Seite auf Luther; beide Zuschreibungen stehen in Bekenntnisschriften. In der Neuzeit reichte die Liste von Napoleon über Hitler bis zu Politikern der Gegenwart. Kein Text des Neuen Testaments ist häufiger dazu benutzt worden, Gegner ins Absolute zu rücken.',
  },
  '2thess 3,6': {
    longAdd:
      'Wer die Betreffenden waren, sagt der Text nur andeutungsweise. Sie arbeiten nicht und treiben Vorwitz – ein Wortspiel im Griechischen, das sich etwa mit „nichts schaffen, aber viel verschaffen“ wiedergeben ließe. Die verbreitetste Erklärung verbindet ihr Verhalten mit der Naherwartung: Wer meint, das Ende sei da, sieht keinen Grund mehr, ein Handwerk zu betreiben. Der Brief selbst hat wenige Verse zuvor gegen die Meinung argumentiert, der Tag des Herrn sei schon gekommen; der Zusammenhang ist also naheliegend, aber nicht ausgesprochen.\n\nEine zweite Erklärung setzt bei der Wirtschaftsform an. In griechischen Städten lebten viele Freie als Klienten von einem Gönner: Man erschien morgens zur Aufwartung, erhielt eine Zuwendung und begleitete den Patron durch den Tag. Das galt nicht als Müßiggang, sondern als anerkanntes Verhältnis. Wenn die Gemeinde solche Beziehungen ersetzte und Wohlhabende Ärmere unterstützten, konnte dieselbe Erwartung entstehen – und mit ihr eine Belastung, die der Brief begrenzt.\n\nDass der Absender auf seine eigene Handarbeit verweist, ist in diesem Zusammenhang ein Argument. Handwerk galt in gebildeten Kreisen als unwürdig; Cicero zählt es zu den unfreien Beschäftigungen, und ein Lehrer, der mit den Händen arbeitete, verlor an Ansehen. Andere Wanderlehrer ließen sich bezahlen oder suchten Gönner. Auf die Werkstatt zu verweisen, war deshalb kein Nebensatz, sondern eine Stellungnahme in einer Statusfrage.\n\nDie Wirkungsgeschichte des Satzes verläuft weitgehend außerhalb der Kirche. Lenin machte ihn zum Grundsatz des Sowjetstaats; er stand in der Verfassung von 1936 und, in abgewandelter Form, in der DDR-Verfassung. Auch die frühen amerikanischen Siedlergemeinschaften beriefen sich auf ihn, und in der Sozialstaatsdebatte wird er bis heute angeführt. Der Text sagt etwas anderes: Er spricht von Menschen, die nicht arbeiten wollen, nicht von solchen, die keine Arbeit finden; er ordnet die Sache einer Gemeinde zu, nicht einem Staat; und er schließt mit der Anweisung, den Betreffenden nicht als Feind zu behandeln.',
    crossRefsAdd: [
      { book: '1thess', chapter: 4, verse: 11, note: 'Arbeitet mit euren Händen' },
      { book: 'apg', chapter: 18, verse: 3, note: 'Das Handwerk des Zeltmachens' },
      { book: '1kor', chapter: 9, verse: 12, note: 'Auf das Recht auf Unterhalt verzichten' },
      { book: '2thess', chapter: 3, verse: 15, note: 'Nicht als Feind, sondern als Bruder' },
    ],
  },
  '2tim 4,6': {
    longAdd:
      'Das Bild vom Trankopfer ist genau gewählt. Beim Opfer wurde Wein neben oder über die Gabe auf den Altar gegossen – eine Beigabe, nicht die Hauptsache; die Tora schreibt sie zu den täglichen Opfern vor, und die griechische wie die römische Religion kannte dieselbe Handlung. Wer sein eigenes Ende so beschreibt, ordnet es einem anderen Geschehen zu, statt es zur Hauptsache zu machen. Dasselbe Bild steht bereits im Philipperbrief, dort ebenfalls im Blick auf einen möglichen Tod.\n\nDas Wort für den Aufbruch stammt aus zwei Bereichen zugleich: Es bezeichnet das Losmachen eines Schiffes vom Ankerplatz und das Abbrechen eines Zeltlagers. Beide Bilder passen zu einem Text, der von Reisen und vorläufigen Behausungen durchzogen ist. Die lateinische Übersetzung wählte resolutio, Auflösung, und gab dem Wort damit einen Klang, den das griechische nicht hat – aus einem Aufbruch wurde ein Zerfall.\n\nDie Wettkampfsprache war allgegenwärtig. In jeder größeren Stadt gab es Wettkämpfe, die Isthmischen Spiele fanden bei Korinth statt, und die Sieger erhielten einen Kranz aus Zweigen – bei den Isthmien aus Fichte, in Olympia aus wildem Ölbaum. Der Kranz war wertlos und alles wert: Er brachte Ehrenplätze, Steuerfreiheit und Standbilder. Der Ausdruck vom Kranz der Gerechtigkeit setzt diese Vorstellung voraus und verschiebt zugleich, wer ihn zuerkennt.\n\nOb der historische Paulus diese Zeilen schrieb, ist die Streitfrage der Pastoralbriefe. Wortschatz und Stil weichen ab, die Gemeindeverhältnisse wirken später, und die Reisenotizen lassen sich in keine bekannte Chronologie einfügen. Wer den Brief für ein Schreiben eines Schülers hält, liest den Abschnitt als Vermächtnis, das dem Lehrer in den Mund gelegt wird – eine in der Antike anerkannte literarische Form. Wer an der Verfasserschaft festhält, sieht darin die letzten erhaltenen Zeilen eines Mannes vor seiner Hinrichtung. Der Text selbst gibt keine Entscheidung her, und seine Wirkung in der Sterbeliturgie ist von der Antwort unabhängig geblieben.',
  },
  'tit 2,11': {
    longAdd:
      'Der Abschnitt ist in wenigen Sätzen dicht gebaut. Er nennt zweimal ein Erscheinen – das vergangene und das erwartete –, dazwischen steht das gegenwärtige Leben. Diese Dreiteilung, in der Vergangenheit und Zukunft die Gegenwart einrahmen, ist die Grundform christlicher Zeitrechnung überhaupt und findet sich in Liedern, Bekenntnissen und Gebeten der ganzen Kirchengeschichte wieder.\n\nDas Wort für die Erscheinung gehörte zur Sprache der Herrscherverehrung. Der Besuch eines Kaisers in einer Stadt wurde als Epiphanie gefeiert, mit Gesandtschaften, Bekränzung und Ehreninschriften; der Seleukidenkönig Antiochus IV. führte den Beinamen Epiphanes im Titel. Dass derselbe Begriff hier auf ein Kind in Bethlehem und auf eine erwartete Wiederkunft angewandt wird, ist eine Übernahme mit Hintersinn. Das kirchliche Fest der Epiphanie am 6. Januar trägt bis heute diesen Namen.\n\nDas Verb, das Luther mit züchtigen übersetzt, meint erziehen. Es ist von dem Wort für Kind abgeleitet und bezeichnet die gesamte Ausbildung eines jungen Menschen – Unterricht, Gewöhnung und, wo nötig, Strafe. Die griechische Bildungslehre hieß danach paideia und war der Inbegriff dessen, was einen Menschen zum Bürger machte. Dass die Gnade selbst diese Rolle übernimmt, ist die eigentliche Aussage des Abschnitts: Sie ist keine Zusage, die das Verhalten unberührt lässt, sondern eine, die es formt.\n\nDer Vers, der die Reihe abschließt, verlangt vom Empfänger, mit ganzem Ernst zu reden und sich von niemandem verachten zu lassen. Titus war offenbar jung oder stand ohne festen Rückhalt; ähnliche Sätze stehen in den Timotheusbriefen. In einer Gesellschaft, in der Alter und Herkunft über das Gehör entschieden, war das ein reales Problem – und die Ermahnung setzt voraus, dass die Verkündigung nicht von der Stellung des Verkündigers abhängt.',
  },
  'tit 3,3': {
    longAdd:
      'Der Abschnitt ist als Gegenüberstellung gebaut: erst was wir waren, dann was geschehen ist. Diese Form – einst und jetzt – gehört zur frühchristlichen Bekehrungssprache und findet sich mehrfach in den Briefen. Ihre Funktion ist doppelt: Sie beschreibt einen Bruch und verhindert zugleich die Überheblichkeit, denn wer sich an das Einst erinnert, kann über die Gegenwärtigen nicht urteilen. Genau dies begründet im Zusammenhang die Anweisung, gegen alle Menschen sanftmütig zu sein.\n\nDie Verse vier bis sieben gelten der Forschung überwiegend als Zitat. Sie heben sich im Satzbau vom Übrigen ab, enthalten Wörter, die sonst nirgends im Brief vorkommen, und schließen mit einer Formel, die den Abschnitt als zuverlässiges Wort bezeichnet – eine Wendung, die in den Pastoralbriefen mehrfach Zitate einleitet. Wahrscheinlich handelt es sich um ein Tauflied oder eine Bekenntnisformel aus der Gemeindeliturgie.\n\nDas Wort für Menschenfreundlichkeit war ein politischer Begriff. Hellenistische Könige und römische Kaiser wurden auf Inschriften dafür gerühmt; die Eigenschaft gehörte zum Herrscherlob wie Gerechtigkeit und Tapferkeit und meinte konkret die Zuwendung eines Mächtigen zu den Geringeren – Steuernachlässe, Getreidespenden, Begnadigungen. Der Brief legt den Titel Gott bei und behält die Richtung bei: von oben nach unten, ohne Gegenleistung.\n\nDie Formel vom Bad der Wiedergeburt hat die Sakramentenlehre geprägt und zugleich eine Frage aufgeworfen. Waschungen kannten auch die Mysterienkulte: Wer in die Isismysterien aufgenommen wurde, badete zuvor, und der Mithraskult kannte Reinigungsriten. Die Religionsgeschichte des frühen 20. Jahrhunderts hat daraus eine Abhängigkeit ableiten wollen; die neuere Forschung ist zurückhaltender und verweist auf die jüdischen Tauchbäder, von denen in Jerusalem und Qumran zahlreiche ausgegraben sind. Das Wort für Wiedergeburt selbst stammt aus der stoischen Kosmologie, wo es die Erneuerung der Welt nach dem Weltbrand bezeichnet, und steht im Matthäusevangelium für die kommende Welt – eine Herkunft, die den Blick vom Einzelnen auf das Ganze weitet.',
    crossRefsAdd: [
      { book: 'eph', chapter: 2, verse: 3, note: 'Dieselbe Einst-und-jetzt-Figur' },
      { book: 'joh', chapter: 3, verse: 5, note: 'Aus Wasser und Geist geboren' },
      { book: 'roem', chapter: 6, verse: 4, note: 'Die Taufe als Begräbnis und Auferstehung' },
      { book: 'tit', chapter: 3, verse: 2, note: 'Die Anweisung, die der Abschnitt begründet' },
    ],
  },
};
