/* Vertiefung: Römerbrief und 1. Korinther */

export const PATCHES = {
  'roem 1,16': {
    longAdd:
      'Der Brief hat einen bestimmten Anlass. Er ist an eine Gemeinde gerichtet, die der Absender nicht gegründet hat und nicht kennt; er kündigt einen Besuch an und eine Reise weiter nach Spanien, für die er Unterstützung sucht. Zugleich steht im Hintergrund ein Konflikt in Rom selbst. Kaiser Claudius hatte um das Jahr 49 Juden aus der Stadt gewiesen – Sueton nennt als Grund Unruhen, die ein gewisser Chrestus angestiftet habe –, und nach dem Tod des Claudius kehrten die Vertriebenen in Gemeinden zurück, die inzwischen überwiegend aus Heidenchristen bestanden. Die Reihenfolge „den Juden vornehmlich und auch den Griechen“ greift genau in diese Lage.\n\nDas Wort Evangelium war vor seiner christlichen Verwendung ein Begriff der Herrschaftssprache. Eine Inschrift aus Priene in Kleinasien, beschlossen 9 vor Christus, nennt den Geburtstag des Augustus den Anfang der Freudenbotschaften für die Welt; Siegesmeldungen und Thronbesteigungen wurden mit demselben Wort verkündet. Wer eine Botschaft über einen hingerichteten Provinzialen so bezeichnet, benutzt einen besetzten Begriff.\n\nDer Ausdruck Gerechtigkeit Gottes ist grammatisch mehrdeutig, und daran hängt viel. Er kann eine Eigenschaft Gottes meinen, eine Gabe, die er verleiht, oder eine Handlung, mit der er Recht schafft. Die griechischen Väter neigten zur ersten Lesart, Luther entschied sich für die zweite, und die Forschung des 20. Jahrhunderts hat die dritte stark gemacht: Gottes Gerechtigkeit sei sein rettendes Eingreifen, wie es die Psalmen und Jesaja beschreiben, wo Gerechtigkeit und Heil parallel stehen. Der Wortlaut trägt alle drei.\n\nDas Zitat aus Habakuk ist im Hebräischen doppelt beziehbar, und die Übersetzungen entscheiden sich verschieden: Lebt der Gerechte aus seinem Glauben, oder lebt, wer durch Glauben gerecht ist? Die griechische Bibel hat an dieser Stelle „aus meinem Glauben“ und meint damit Gottes Treue; die Qumran-Auslegung zu Habakuk bezieht den Vers auf die Treue zum Lehrer der Gerechtigkeit. Paulus zitiert ohne das Possessivpronomen und lässt die Frage offen – was die Auslegungsgeschichte nicht daran gehindert hat, sie immer wieder zu entscheiden.',
  },
  'roem 3,23': {
    longAdd:
      'Der Satz steht am Ende einer langen Beweisführung. Die Kapitel eins bis drei zeigen zuerst, dass die Völker Gott verfehlen, dann, dass auch die Kenntnis des Gesetzes davor nicht schützt, und schließen mit einer Kette von Zitaten aus den Psalmen und Jesaja, die keinen Gerechten kennt. Diese Anordnung ist rhetorisch gebaut: Die Anklage gegen die anderen findet Zustimmung, bevor sie sich gegen die Zustimmenden wendet. Die griechische Diatribe, eine Schulform des Streitgesprächs mit fingiertem Gegner, verwendet genau dieses Verfahren.\n\nDas Wort, das Luther mit Ruhm oder Herrlichkeit wiedergibt, übersetzt das hebräische kabod – ursprünglich Gewicht, dann Ansehen, dann der sichtbare Glanz Gottes. In der jüdischen Auslegung der Zeit gab es die Vorstellung, Adam habe vor dem Fall einen Lichtglanz besessen und ihn verloren; mehrere Texte aus Qumran und die rabbinische Literatur sprechen davon. Der Satz vom Mangeln der Herrlichkeit klingt vor diesem Hintergrund weniger nach moralischem Versagen als nach einem Verlust, der wieder gutgemacht werden kann.\n\nDer zweite Teil des Satzes wechselt in die Rechtssprache. Gerechtfertigt werden ist ein Vorgang vor Gericht: Der Richter spricht frei. Daneben stehen zwei Bilder aus anderen Bereichen – die Erlösung, die aus dem Freikauf von Sklaven und Kriegsgefangenen stammt, und wenige Worte später die Sühne, die auf den Deckel der Bundeslade und den großen Versöhnungstag verweist. Drei Bildwelten in einem Satz: Gericht, Markt, Tempel. Keine erklärt die andere, und der Streit darüber, welche die anderen deuten soll, zieht sich durch die ganze Dogmengeschichte.\n\nDas Wort für „ohne Verdienst“ heißt wörtlich geschenkweise. Dieselbe Vokabel steht in der griechischen Bibel für „grundlos“ – so, wenn im Psalm die Feinde ohne Ursache hassen, und im Johannesevangelium, wo dieser Psalm zitiert wird. Die Doppelbedeutung ist bemerkenswert: Was ohne Gegenleistung gegeben wird, ist aus der Sicht des Rechts auch das, wofür sich kein Grund angeben lässt. Die Reformationszeit hat aus dieser Vokabel eine ihrer Grundunterscheidungen gewonnen.',
  },
  'roem 8,1': {
    longAdd:
      'Die Textgeschichte des Verses ist ein Lehrstück. Die ältesten Handschriften bieten nur den kurzen Satz; jüngere fügen den Zusatz aus Vers vier an, teils in zwei Stufen. Solche Angleichungen sind der häufigste Fehlertyp beim Abschreiben: Ein Schreiber, der den Zusammenhang kennt, ergänzt aus dem Gedächtnis, was er wenige Zeilen später liest. Für den Sinn ist der Unterschied erheblich, denn mit dem Zusatz wird der Freispruch an eine Bedingung geknüpft, ohne ihn nicht. Die Lutherbibel gibt bis heute die längere Form wieder, moderne Ausgaben die kürzere.\n\nDas Wort für Verdammnis gehört in die Gerichtssprache und bezeichnet nicht den Schuldspruch, sondern die Strafe, die auf ihn folgt. Wer verurteilt war, wurde zur Zwangsarbeit, in die Arena oder zum Tod geschickt. Der Satz sagt also nicht, dass niemand schuldig sei, sondern dass die Vollstreckung entfällt – ein Unterschied, den die deutsche Wendung „nichts Verdammliches“ eher verdeckt.\n\nDer Zwiespalt, mit dem das vorige Kapitel schließt, ist eine der umstrittensten Stellen des Neuen Testaments. Wer redet dort in der Ich-Form? Augustinus deutete es in seiner Frühzeit auf den Menschen vor der Taufe und später auf den Christen, der weiterhin gegen sich kämpft; Luther folgte der zweiten Deutung und formte daraus seine Formel vom Gerechten und Sünder zugleich. Die neuere Forschung liest das Ich häufig als rhetorische Figur – die Diatribe kannte das fingierte Ich –, und ein Teil der Ausleger bezieht es auf Israel unter dem Gesetz. Die Entscheidung darüber verändert den Ton des ganzen Briefes.\n\nDas Wort, das Luther mit Fleisch übersetzt, bezeichnete im Griechischen zunächst das Muskelfleisch, dann den Leib, dann die Verwandtschaft; die hebräische Entsprechung meint den vergänglichen Menschen im Gegensatz zu Gott. Bei Paulus tritt eine weitere Bedeutung hinzu: die Ausrichtung auf sich selbst. Dass die abendländische Auslegung daraus über Jahrhunderte eine Abwertung des Körpers und besonders der Sexualität gemacht hat, gilt heute weithin als Fehlübertragung, die durch die Berührung mit platonischen Denkformen begünstigt wurde.',
  },
  'roem 10,9': {
    longAdd:
      'Formelhafte Sätze wie dieser lassen sich an bestimmten Merkmalen erkennen: knapper Bau, feste Wortpaare, Wendungen, die sonst bei diesem Verfasser nicht vorkommen. Die Forschung hat mehrere solcher Stücke im Neuen Testament ausgemacht – die Auferstehungsformel im ersten Korintherbrief, den Christushymnus im Philipperbrief, den Bekenntnissatz im ersten Timotheusbrief. Sie sind älter als die Briefe, in denen sie stehen, und gehören damit zu den frühesten fassbaren Texten des Christentums.\n\nDer Titel Herr war im griechischsprachigen Osten mehrfach besetzt. Er stand für den Hausherrn gegenüber Sklaven, für Gottheiten in den Mysterienkulten und für den Kaiser: Papyri aus Ägypten nennen Nero und seine Nachfolger so, und Eide wurden bei ihrem Namen geschworen. Zugleich war er in der griechischen Bibel die feste Wiedergabe des Gottesnamens, den man nicht aussprach. Wer den Satz sagte, verband deshalb zwei Linien – eine gottesdienstliche und eine politische –, ohne dass die zweite ausgesprochen werden musste.\n\nDie Reihenfolge im Vers ist auffällig. Zuerst steht das Bekennen mit dem Mund, dann das Glauben im Herzen; im nächsten Vers ist sie umgekehrt. Ausleger sehen darin eine Stilfigur, bei der die Glieder über Kreuz wieder aufgenommen werden – ein Kunstmittel, das der Text mehrfach benutzt. Sachlich hebt es die Rangfolge auf: Weder ist das Bekenntnis eine Folge des Glaubens noch umgekehrt; beide gehören zusammen.\n\nDer Zusammenhang macht aus dem Satz etwas anderes, als seine Verwendung nahelegt. Die Kapitel neun bis elf handeln von der Frage, warum die Mehrheit Israels die Botschaft nicht angenommen hat, und enden mit der Aussage, dass Gottes Zusagen an sein Volk nicht widerrufen sind. Der Bekenntnissatz steht mitten in dieser Erörterung und wird sofort mit einem Zitat aus Joel verbunden, wonach jeder gerettet wird, der den Namen des Herrn anruft. Ihn aus diesem Zusammenhang zu lösen und zur Bedingung einer Einzelbekehrung zu machen, ändert seine Richtung – eine Kritik, die vor allem an der Praxis des Übergabegebets geäußert wird.',
  },
  'roem 12,1': {
    longAdd:
      'Opfer waren die selbstverständliche Form von Religion. In Jerusalem wurden täglich zwei Lämmer dargebracht, an Festtagen ein Vielfaches; in den Städten des Reiches gab es Tempel an jeder größeren Straße, und Schlachtung, Braten und Verteilen gehörten zum Stadtbild. Fleisch aß man weitgehend nur bei solchen Anlässen. Wer von einem Opfer sprach, sprach von etwas Alltäglichem und zugleich Blutigem – ein Zusammenhang, der modernen Lesern fehlt und ohne den der Satz seine Schärfe verliert.\n\nDie Verschiebung, die der Vers vornimmt, hat Vorläufer. Die Propheten hatten Opfer ohne Gerechtigkeit verworfen, die Psalmen sprechen vom zerbrochenen Geist als dem Opfer, das Gott gefällt, und die Qumran-Gemeinde, die den Tempel für verunreinigt hielt, verstand ihr eigenes Leben als Ersatzopfer. Auch die griechische Philosophie kannte den Gedanken: Bei den Stoikern und in den hermetischen Schriften erscheint das vernunftgemäße Opfer, das ohne Tier auskommt. Der Vers steht in dieser doppelten Linie.\n\nDas umstrittene Wort logikos verbindet beide. Es leitet sich von logos her und kann vernunftgemäß, wortgemäß oder sachgemäß bedeuten. Wer die philosophische Linie betont, übersetzt vernünftig; wer die biblische betont, übersetzt wortgemäß und versteht das Opfer als Antwort auf die vorher dargelegte Botschaft. Die Lutherübersetzung wählte das erste, die meisten neueren Ausgaben schwanken. Im ersten Petrusbrief steht dasselbe Wort für die Milch, nach der Neugeborene verlangen – ein Beleg dafür, wie weit es reicht.\n\nDass die Leiber genannt werden und nicht die Seelen, ist keine Nebensache. Der Leib ist bei Paulus der Ort, an dem ein Mensch für andere zugänglich ist: an ihm zeigt sich Zugehörigkeit, mit ihm wird gearbeitet, an ihm wird gestraft. Ein Opfer aus Leibern meint deshalb nicht Innerlichkeit, sondern das Gegenteil – Arbeit, Umgang, Geld, Körperlichkeit. Der Gedanke, dass Gottesdienst am Werktag stattfindet, ist aus dieser Beobachtung gewonnen und hat im 20. Jahrhundert die evangelische Rede vom Gottesdienst im Alltag der Welt begründet.',
  },
  'roem 12,2': {
    longAdd:
      'Was Nichtanpassung praktisch hieß, lässt sich benennen. Zum städtischen Leben gehörten Opferfeste, Prozessionen, Vereinsmahlzeiten, Gladiatorenspiele und Eide bei den Göttern; Handwerkerzünfte hatten Schutzgottheiten, und Beförderungen im öffentlichen Dienst waren mit kultischen Pflichten verbunden. Wer fernblieb, verlor Aufträge, Beziehungen und Ansehen. Plinius der Jüngere schreibt zwei Generationen später an den Kaiser, in seiner Provinz seien die Tempel verödet gewesen und das Opferfleisch unverkäuflich – ein wirtschaftlicher Vorgang, der zeigt, wie sichtbar solche Verweigerung war.\n\nDie beiden Verben sind sorgfältig gewählt. Das erste ist von schema abgeleitet, der äußeren Gestalt, die ein Ding annimmt; das zweite von morphe, der Gestalt, die es hat. Ob diese Unterscheidung im Griechischen der Zeit noch trug, ist umstritten – die Wörter überschneiden sich weitgehend –, doch der Gegensatz von Anpassen und Umgestaltetwerden bleibt. Dasselbe zweite Verb steht in den Evangelien für die Verklärung und im zweiten Korintherbrief für die Verwandlung derer, die den Herrn anschauen.\n\nDas Ziel ist ein Urteilsvermögen, kein Regelwerk. Das Wort für prüfen stammt aus der Metallprobe: Münzen wurden auf Echtheit getestet, weil Falschgeld und untergewichtige Stücke verbreitet waren; ein Prüfer hieß dokimastes, und Städte stellten solche Beamten an. Was der Vers verlangt, ist damit die Fähigkeit, im Einzelfall zu unterscheiden – eine Anforderung, die höher liegt als Gehorsam und die voraussetzt, dass die Angeredeten selbst entscheiden können.\n\nDie Verbindung von Absonderung und Urteilsfähigkeit hat eine ungleiche Wirkungsgeschichte. Die täuferischen Gemeinden des 16. Jahrhunderts machten die Absonderung zum Kennzeichen und regelten Kleidung, Eid und Waffendienst; ihre Nachfahren tun es teilweise bis heute. Andere Traditionen haben die zweite Hälfte betont und daraus eine Ethik der Unterscheidung entwickelt, die sich gerade gegen feste Regeln richtet. Beide berufen sich auf denselben Vers, und die Spannung zwischen ihnen ist in ihm angelegt.',
  },
  '1kor 1,18': {
    longAdd:
      'Über die Kreuzigung schweigen die antiken Quellen weitgehend, und das hat einen Grund: Sie galt als so schändlich, dass die gebildete Literatur sie nicht ausführlich behandelte. Was bekannt ist, stammt aus Gerichtsreden, Militärberichten und beiläufigen Erwähnungen. Josephus, der als Augenzeuge über die Belagerung Jerusalems schreibt, nennt sie den erbärmlichsten Tod. Der einzige archäologisch gesicherte Fund eines Gekreuzigten stammt aus einem Grab bei Jerusalem, entdeckt 1968: ein Fersenbein, durch das ein Nagel getrieben war, der sich im Holz verbogen hatte und deshalb nicht mehr entfernt werden konnte.\n\nDie Provokation lag nicht nur in der Hinrichtungsart, sondern in der Verbindung mit einem Heilsanspruch. Für jüdische Hörer stand im Gesetz, dass ein an das Holz Gehängter verflucht sei – ein Einwand, den der Galaterbrief ausdrücklich aufgreift. Für griechisch gebildete Hörer war die Vorstellung eines leidenden und sterbenden Gottes unvereinbar mit dem, was Philosophie über das Göttliche lehrte: Unwandelbarkeit und Leidensunfähigkeit. Der Satz von der Torheit ist deshalb keine Übertreibung, sondern die zutreffende Beschreibung der Wirkung.\n\nKorinth machte die Sache schwieriger. Die Stadt war 146 vor Christus von Rom zerstört und hundert Jahre später als Kolonie neu gegründet worden, besiedelt vor allem mit Freigelassenen. Sie hatte keinen alten Adel, dafür rasch erworbenen Reichtum, die zweitgrößten Spiele Griechenlands und einen ausgeprägten Wettbewerb um Ansehen. Wanderredner traten auf wie heute Künstler auf Tournee, und Rhetorik war das Prestigefach. In einer solchen Stadt eine Botschaft ohne Redeschmuck über einen Hingerichteten vorzutragen, war eine bewusste Entscheidung, und die Gemeinde nahm daran Anstoß.\n\nDie beiden Wörter für die Hörenden stehen im Griechischen in der Verlaufsform: die verloren gehen und die gerettet werden. Es sind keine feststehenden Gruppen, sondern Vorgänge, die noch laufen. Diese grammatische Beobachtung hat in der Auslegung Gewicht bekommen, weil sie der Lesart entgegensteht, der Vers teile die Menschheit endgültig in zwei Lager. Was unterschieden wird, ist die Wirkung derselben Botschaft, nicht ein Bestand an Personen.',
  },
  '1kor 10,13': {
    longAdd:
      'Die konkrete Frage, um die es geht, war für die Gemeinde folgenreich. In Korinth stand ein großer Teil des Fleischs, das auf den Markt kam, zuvor auf einem Altar; Ausgrabungen im Bezirk des Asklepios haben Speiseräume freigelegt, in denen Gäste an Tischen um einen Innenhof lagen. Einladungen zu solchen Mahlzeiten waren Teil des gesellschaftlichen Lebens – Papyrusbriefe überliefern den Wortlaut: Man lädt zum Mahl des Herrn Serapis. Wer ablehnte, sagte Geschäftspartnern, Zunftgenossen und Verwandten ab.\n\nDas Wort für Versuchung deckt zwei Vorgänge ab, die im Deutschen auseinandertreten: die Verlockung zum Falschen und die Prüfung, die jemandem auferlegt wird. Dieselbe Vokabel steht in der Wüstenerzählung, wo Gott das Volk prüft und das Volk Gott versucht, und in der Vaterunserbitte, die seit jeher Schwierigkeiten macht – im Jahr 2019 hat Papst Franziskus die italienische Fassung deshalb ändern lassen. Der Jakobusbrief zieht ausdrücklich die Grenze: Gott versucht niemanden.\n\nDie Warnung davor gibt dem Vers seine Richtung. Paulus hat gerade an die Wüstengeneration erinnert – an das goldene Kalb, das Murren, die Schlangen – und daraus gefolgert, dass Zugehörigkeit allein nicht schützt. Der Satz unmittelbar vor dem Vers lautet, wer meint, er stehe, möge zusehen, dass er nicht falle. Der Trost ist also an eine Warnung gebunden, und der Satz unmittelbar danach zieht die praktische Folgerung: Flieht den Götzendienst. Der Ausweg, von dem der Vers spricht, wird dort benannt, und er heißt nicht Aushalten, sondern Weggehen.\n\nDas Wort für diesen Ausweg stammt aus der Geographie und bezeichnet den Ausgang aus einem Engpass, einer Schlucht, eines Passes; die griechische Bibel gebraucht es für den Ausgang aus Ägypten. Die verbreitete Redensart, Gott lege niemandem mehr auf, als er tragen könne, sagt etwas anderes: Sie spricht vom Maß der Last, der Vers von einer Tür. Der Unterschied ist in der Seelsorge erheblich, weil die Redensart Menschen, die an einer Belastung zerbrechen, ihr Scheitern als Widerlegung vorhält.',
  },
};
